### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#104]
In the login page, there is a "Forgot Password?" link that sends you to a page where you need to enter the username AND email address related to the account.

When you submit, it checks if the information is true. If it is not, it tells you it is the wrong information.

If it is correct, it sends the email with the password reset information.

**Comment by rr-** [comment]
I'll ask for the email only; the user may forget their username.

**Comment by Klona13** [comment]
I can submit and update my password, despite the new ones not matching. It updates the password using the one entered in the first "new password" field. The second new password field needs to prevent updating the form from updating if it doesn't match the first new password field.
![image](https://user-images.githubusercontent.com/93257509/158904790-69651fd1-bea2-4d34-accc-5bb3a96d9430.png)

**Comment by Klona13** [comment]
I realized I was testing the wrong form.

1. I sent a PW reset for Klona's account, but I used AODfan's email. It sent an email to AODfan instead of not doing anything.

2. Like the issue in the previous post the new passwords don't have to match for the form to submit.
