### ISSUE TITLE
Home Page - Statistics

### ISSUE THREAD

**Issue by rr-** [rr-/trcustoms#105]
Detailed in #86

**Comment by rr-** [comment]
The reference seems to be outdated @Klona13

**Comment by Klona13** [comment]
> The reference seems to be outdated @Klona13

Main skeleton updated, for detailed function see:

![image](https://user-images.githubusercontent.com/93257509/156452096-722efc03-f228-4e11-aeb1-b03ba2f65d16.png)

Example when clicked on:
![image](https://user-images.githubusercontent.com/93257509/156452146-8bd2a9e8-8426-43ac-921c-1121eda706be.png)
The selection turns to the selected text color (white in the dark mode) and a line points to the text with the info.

**Comment by Klona13** [comment]
Reviews: <Total individual reviews posted> (<average>/level)
All Level Ratings show each rating tier (11). When selected, it shows the number of levels in that rating and %. Levels with NO rating are NOT counted here.

Walkthrough shows total walkthroughs (all of them).
'Lined bar' is Text Guide
'Solid bar' is Video Guide
'Empty bar' is Missing
Shows the number and %.

**Comment by Klona13** [comment]
Red:
![image](https://user-images.githubusercontent.com/93257509/156667974-0d0dc78b-4108-4dde-ab4a-035ee8c19492.png)

Green:
![image](https://user-images.githubusercontent.com/93257509/156668021-795269e1-08ae-4298-95c4-8204d0c81b65.png)

When you hover, maybe something like this:
![image](https://user-images.githubusercontent.com/93257509/156668433-ff95c8fb-f8a3-4d00-92b1-677054024e81.png)

And remember to move the hover text below so there isn't a ghost margin.

**Comment by Klona13** [comment]
Final touch?
![image](https://user-images.githubusercontent.com/93257509/156789359-b11b8068-70d6-41c4-b717-be2ee0aec854.png)

**Comment by rr-** [comment]
We don't do it anywhere else though; it'll create inconsistency with the level and user page sidebars. Should I do it just here or everywhere?

**Comment by Klona13** [comment]
It's meant to signify that this is under the "total levels".

The statistics have 3 sections:
Levels
Reviews
Walkthroughs

**Comment by rr-** [comment]
I disagree with this choice as it creates an inconsistency with other sidebar elements – some will be aligned to the right, some to the left, and it will look random.

**Comment by Klona13** [comment]
Alright, we can keep it aligned to the left but we should at least give it bullet points.
And move TEN under TR5 please.

**Comment by Klona13** [comment]
^ @rr-

**Comment by rr-** [comment]
I didn' t forget about it, I see myself assigned.
