### ISSUE TITLE
Email text same color as button

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#107]
The text blends in cause it's blue. :(
It could be white?
![image](https://user-images.githubusercontent.com/93257509/156602149-bfeb07d2-8593-4d4b-9797-601a8ef6257b.png)

**Comment by rr-** [comment]
It is set to white. We now just need to address every mailbox provider's style overrides so that it actually f… stays white.

**Comment by Klona13** [comment]
Goddamit.
Would an image work?

If not, we can settle for grey box with the normal blue link.

**Comment by rr-** [comment]
Nah, I'll do something about it. Just venting :)
