### ISSUE TITLE
Improve anonymous user avatar

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#118]
The current anonymous avatar looks very poorly. We should have something a bit more professional-looking, that is ideally compatible with both dark and light themes (OK for transparent PNGs). 

I don't want the avatar to relate to reboot Lara.

**Comment by Klona13** [comment]
I posted a request in the server to see if anybody will be able to come up with something.

**Comment by Klona13** [comment]
Looking at it again. I feel like the grey border added some depth and it looked better with it.
