### ISSUE TITLE
Theme - Lettuce panel issues

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#119]
The left sidepane shouldn't have a border, but the News border looks really out of place. It also affects the reviews area in the level page.
![image](https://user-images.githubusercontent.com/93257509/158063782-bfaa04e8-2416-4685-97b6-cc224a1815c9.png)
![image](https://user-images.githubusercontent.com/93257509/158063991-64bb27fc-2d9e-4232-82ae-cc02779e9d19.png)

Instead we could do this (the text looks a bit fucked cause this is an edit with the bucket tool in paint editor, not a recolor from elements console):
![image](https://user-images.githubusercontent.com/93257509/158063714-830160fe-19ef-4786-a1c5-c41981f7ff42.png)
![image](https://user-images.githubusercontent.com/93257509/158064017-2d40c2e3-9fba-4236-b8cd-6b63c65ab497.png)
The black text against the light green would look like this:
![image](https://user-images.githubusercontent.com/93257509/158082841-455a0f8d-ea28-47e8-8456-1ff70027ab95.png)

**Comment by rr-** [comment]
@Klona13 is it ok for me not to include a background for the media section as well?

Otherwise I'd have to make a separate rule just for lettuce for this one panel.

**Comment by Klona13** [comment]
You are right.
I think I had it this way while editing. I posted the version with it by accident... my bad.
