### ISSUE TITLE
Mod Page Accessibility

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#124]
The Moderators page can be seen even if you aren't logged in as a mod or logged in at all.
The only people who should be able to access the page are moderators / super users

**Comment by Klona13** [comment]
I think they shouldn't even see the page at all. Like give them one of the error pages?
![image](https://user-images.githubusercontent.com/93257509/159102255-54fbc021-7892-4ce3-8e51-70f48e8fd411.png)
![image](https://user-images.githubusercontent.com/93257509/159102261-77c8366f-dba4-4ec2-806a-42b316e327fb.png)

**Comment by rr-** [comment]
Cosmetic issue. Won't fix.
