### ISSUE TITLE
Mod Page - Filter Sidebar

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#125]
Can search by name separately for:
- Author
- Object

For Change column, there are tick boxes.
User States
- Created
- Approved
- Rejected
- Banned
- Unbanned

Level States
- Created
- Edited
- Approved
- Rejected

Review States
- Posted
- Edited

Tag States
- Created
- Deleted
- Merged
- Expired

**Comment by Klona13** [comment]
For User States: Approved is actually Activated.

**Comment by rr-** [comment]
Fix'd

**Comment by Klona13** [comment]
Change this too:
Rejected (reason: Email not activated)

to

Rejected (reason: Unconfirmed Email)

Cause "activated" filter picks it up too.
