### ISSUE TITLE
Page attempts a GET request when not logged in

### ISSUE THREAD

**Issue by Raildex** [rr-/trcustoms#130]
When I am *not* logged in, the page still tries to GET `api/users/me` which results with a 401.
No cookie is set, so that request should be avoided.

![request](https://user-images.githubusercontent.com/14938934/159643917-5783cb28-17a8-4f6f-97d4-13b20d2dc03e.JPG)

**Comment by Klona13** [comment]
@Raildex see this please

**Comment by Raildex** [comment]
Fixed.
