### ISSUE TITLE
No thumbnails are shown on the level list

### ISSUE THREAD

**Issue by Raildex** [rr-/trcustoms#134]
There are no thumbnails for me and the layout is corrupted?
![list](https://user-images.githubusercontent.com/14938934/159644513-e6f11d90-2ca1-4157-885c-20dc36e41e9e.JPG)

**Comment by Raildex** [comment]
I receive "Request aborted"
![Unbenannt](https://user-images.githubusercontent.com/14938934/159645069-d27fb328-0e1a-4f7e-8875-88360a7aa596.jpg)

**Comment by Klona13** [comment]
I never had this issue on W10 or on my Android phone.

**Comment by Kubsy** [comment]
I didn't have that issue.

**Comment by rr-** [comment]
@Raildex what browser are you using?

**Comment by Raildex** [comment]
> @Raildex what browser are you using? Are you able to reproduce this issue? In inspector the error is about favicon, not the images.

I am on Win10 Firefox

**Comment by Kubsy** [comment]
Yeah Zreen was on Firefox. Guess it happens only on that browser.

**Comment by Klona13** [comment]
@Raildex can you please test again?

**Comment by Raildex** [comment]
Fixed.
