### ISSUE TITLE
Do we really need a level verification?

### ISSUE THREAD

**Issue by Raildex** [rr-/trcustoms#136]
This is personal opinion,
but do we really need *level* verification?

The users are already verified by the staff, why can't we just upload a level and let it be? Why does it have to be verified before it gets publicly visible?

TRCustoms will probably have more than a single person for verification, but if you consider holidays - where it is likely that staff members are absent - then authors may still wait for several days when their level gets publicly visible.
Whats the point of the verification anyway?

When the users are already verfied, aren't the levels also automatically verified?
That would be a very big advantage over other custom level hosting sites.

Moderation should happen when a level is uploaded (to disallow illegal content etc) of course, but not before it becomes publicly visible in my opinion

**Comment by Kubsy** [comment]
Well. there will be moderators more than 1 I believe and you also don't want spammers to spam level submissions and troll for example post 10 NSFW stuff

**Comment by Klona13** [comment]
It's not a bad idea to be vigilant in these cases.
We can verify new accounts who weren't on TRLE.net before, but there is just no guarantee they're not trolls.
