### ISSUE TITLE
Layout not optimized for mobile

### ISSUE THREAD

**Issue by Raildex** [rr-/TRCustoms#137]
Idk how relevant that is; The layout on mobile is not optimized![image](https://user-images.githubusercontent.com/14938934/159700769-5f3c4077-9cb9-40f2-998d-e8086a80d422.png)

**Comment by Klona13** [comment]
Let's keep this for post-launch.

**Comment by Klona13** [comment]
https://user-images.githubusercontent.com/93257509/162064363-316cd0ee-b20f-4cad-93e8-f2dd9374032c.mp4

Optimization Issues:
0:01 - Homepage can scroll horizontally, that shouldnt happen
0:15 - Level listing also scrolls horizontally, ^
0:25 - Cover images are too small and are cropped, can make them bigger and maintain 4:3.
0:42 - Profile page side bar is not optimized like the other pages, allowing the page to scroll horizontally

The level listing issue extends to the desktop version as well on staging:
![image](https://user-images.githubusercontent.com/93257509/162066619-b3fe579a-ba08-465a-84a7-12357f7bebc1.png)

It still looks perfect on production:
![image](https://user-images.githubusercontent.com/93257509/162066507-3c5753b3-1102-4de1-b5bf-ff59370c7566.png)

**Comment by Klona13** [comment]
I completely forgot to mention this the other day...
See how the picture appears when you click on it. Can't zoom or move it or anything.
![Screenshot_20220409-040620_Chrome](https://user-images.githubusercontent.com/93257509/162548299-a700fd85-3fc6-47c0-87b2-54be5e718b66.jpg)
![Screenshot_20220409-040610_Chrome](https://user-images.githubusercontent.com/93257509/162548302-24f6206d-e6c6-49ee-8305-6d5483ae6fdd.jpg)

**Comment by rr-** [comment]
What do you expect me to do here?

**Comment by Klona13** [comment]
When you click on the image from the level page, it opens as you see in the second picture.

When you click on the image, it appears like that. The sides of it are cropped like in the picture and you cant zoom out to reveal the cropped area.

Zooming in and out works now, but you can't zoom out beyond the point in the pic above. The image should go full screen properly without being cropped like that.

**Comment by rr-** [comment]
>The image should go full screen properly without being cropped like that.

What does it mean "go full screen properly"?
When the screen is in portrait mode you want the sides of the image to touch the sides of the screen? It'll be really small then. What about the arrows? They'll make the image even smaller.

Or do you want to open the images in a new tab instead and use native browser capabilities?

**Comment by Klona13** [comment]
In landscape viewing, it's perfect. So IF it's not possible to force landscape mode for image viewing then...

> When the screen is in portrait mode you want the sides of the image to touch the sides of the screen? It'll be really small then.

Yes, it's better than having the image cropped as shown in the video and unable to zoom out further.

> What about the arrows? They'll make the image even smaller.

Yes, we keep the arrows.
Landscape mode arrows are perfect, but for portait mode, move both arrows below the image.

> Or do you want to open the images in a new tab instead and use native browser capabilities?

Nooo

**Comment by rr-** [comment]
The image was too tiny, I changed the chevrons (< > icons) to be displayed over the image.
Further specialization for the gallery on mobile (such as swiping) should be tackled in a separate, low priority ticket.

**Comment by Klona13** [comment]
Ok. For now it's good.
