### ISSUE TITLE
User list and user links access issue

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#144]
Everyone signed in has access to the user list.
And if you are signed out, you can't click on usernames to visit their profile.

**Comment by rr-** [comment]
@Klona13 I don't understand, can you show screenshots what you mean?

User profiles are not available for public by design

**Comment by Klona13** [comment]
I find it strange to limit viewing profiles to registered users only. Forcing people to make an account just to see someone's profile sounds wrong.

For the users tab, I think we should remove it from the nav bar and move the users page into the mod page as a button "Full User List" placed at the top of the sidebar.

**Comment by rr-** [comment]
OK but that's a feature request.
