### ISSUE TITLE
Media limit on level page

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#145]
Currently users can have 11 media slots of  (9 screenshots/ 2 youtube links) on the level page.

We have agreed to limit this to a maximum of 9 slots shared by both media types.

Add a media slot counter that starts at 9 (shared by screenshot/youtube links).

**Comment by Klona13** [comment]
You can still add too many media and there's no warning in the upload page.
![image](https://user-images.githubusercontent.com/93257509/159901919-ad71bb41-35d6-43dc-bbfe-8dcff5842f5e.png)
![image](https://user-images.githubusercontent.com/93257509/159902139-ed797887-75be-42dc-9dd8-3182c0ed68bb.png)

**Comment by Klona13** [comment]
Why can I suddenly upload pngs? I thought we limited this to jpgs?
![image](https://user-images.githubusercontent.com/93257509/160024753-80ad087b-5aef-4e1f-be9f-f1f04665707b.png)

**Comment by rr-** [comment]
Because I decided we can.

**Comment by Klona13** [comment]
It's important to be jpeg.
These PNGs can add up very quickly. And they're not gonna be 2 MB if people take high res shots.

**Comment by rr-** [comment]
Well that's on me. Please make a separate issue instead of discussing this in an irrelevant ticket.

**Comment by Klona13** [comment]
Yes
