### ISSUE TITLE
Missing downloads

### ISSUE THREAD

**Issue by MatieTR** [rr-/trcustoms#153]
Downloads are missing for levels with external downloads, such as BtB2018 and BtB2020.

 - https://trcustoms.org/levels?search=btb2018

 - https://trcustoms.org/levels?search=btb2020

**Comment by rr-** [comment]
I think we have already fixed this but it only needs re-scraping.

**Comment by Kubsy** [comment]
yeah btb has separate webpages so scrap is needed I think

**Comment by rr-** [comment]
Restored website URLs. Klona will handle getting the files in #88.
