### ISSUE TITLE
Fade for media showcase

### ISSUE THREAD

**Issue by MatieTR** [rr-/trcustoms#154]
A fade or some sort of a background/layer over the web content would be nice when viewing media on level pages. Flipping through images causes the text and web content in the background to flicker through, ruining user experience a little bit.

![fade](https://user-images.githubusercontent.com/48183219/159990731-fb9b7e77-938b-4879-abaf-2bc2772d48ae.jpg)

**Comment by Klona13** [comment]
@MatieTR Could you please check. The fades have been removed as they would require too much time to refactor.
Now it should just switch instantly without the fade, which is better IMO.

**Comment by MatieTR** [comment]
Fade was still there for me until I hit Shift + F5, now it's fine and images flip with no flicker, which is much better for the time being!

I do get a new bug though, once I'm done flipping through the images the media showcase just closes by itself instead of going back to the first item and the entire image gets highlighted as it disappears. When I open any image again, it's highlighted in blue and it's hard to get rid of.

![image](https://user-images.githubusercontent.com/48183219/160214886-96102770-07db-44ca-88b7-df79f457adb1.png)

**Comment by Klona13** [comment]
I get this too, it's pretty annoying.

**Comment by rr-** [comment]
Well I don't get this. What does "I'm done flipping through the images" mean.

**Comment by Klona13** [comment]
> LMK if I should prevent the popup from closing when clicking on the arrow area.

Yes for this.

**Comment by Kubsy** [comment]
There's still no fade for me

**Comment by Klona13** [comment]
> There's still no fade for me

Please read the last few comments. The fade has been removed and we are testing for another thing.

**Comment by Kubsy** [comment]
Ah ok in that case theres no fade
![image](https://user-images.githubusercontent.com/80340234/160366783-c5d42ff1-b2a0-4be2-afd2-d807e5821d89.png)

**Comment by Kubsy** [comment]
Wbk?
