### ISSUE TITLE
Error 403 when editing own level

### ISSUE THREAD

**Issue by MatieTR** [rr-/trcustoms#156]
Getting a 403 error when trying to update level info.

**Comment by MatieTR** [comment]
I don't get an error anymore and changes went through fine, but someone with normal privileges will have to try as well to see if it works for them, too.

**Comment by Klona13** [comment]
> I don't get an error anymore and changes went through fine, but someone with normal privileges will have to try as well to see if it works for them, too.

I removed your mod privileges when I messaged you on discord as the mod system is still being finalized.

**Comment by MatieTR** [comment]
Oh okay, seemed to have stayed until I hit Shift + F5 just now. Can confirm that this works now.
