### ISSUE TITLE
The statistics on the home page got accidentally tabbed

### ISSUE THREAD

**Issue by Kubsy** [rr-/trcustoms#157]
![image](https://user-images.githubusercontent.com/80340234/160009796-339aa5fa-6ec4-40b1-adf0-500dd444b89b.png)

**Comment by Kubsy** [comment]
![image](https://user-images.githubusercontent.com/80340234/160009850-6927bbdb-e1c7-4813-b812-edbd4ee5317d.png)

**Comment by Klona13** [comment]
Still there, but less obvious:
![image](https://user-images.githubusercontent.com/93257509/160198473-2d33ff0a-495f-413c-819d-499f69e679f6.png)

![image](https://user-images.githubusercontent.com/93257509/160198419-716cfc9b-eb53-45a7-aa33-9b0bf9c8a48b.png)

Disabling the highlighted part makes it look right:
![image](https://user-images.githubusercontent.com/93257509/160198536-a544971b-908f-4f7e-9ec1-55375f75f180.png)
