### ISSUE TITLE
Review Edit permissions removed from mods

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#160]
Mods can't edit reviews anymore. They shouldn't see the remove review button.

**Comment by rr-** [comment]
I think this works as intended without needing any change in the code. Can you confirm?

**Comment by Klona13** [comment]
No, as you requested this ticket to be repurposed for the function it mentions now.
It used to be about the email not reaching the reviewer, but this shouldn't be necessary anymore as mods cannot edit a review after this ticket is developed.

**Comment by rr-** [comment]
I don't get your comment.

Nobody can edit the reviews unless they're author, a staff user or have a privilege assigned by hand in django admin.

**Comment by rr-** [comment]
We do, yeah :D 

Can you show me the list of permissions you want moderators to have?
Everything they currently can except editing people's reviews?

**Comment by Klona13** [comment]
Yeah, everything they can currently do except editing reviews.
It's something that can easily be abused.
