### ISSUE TITLE
Level Upload - Media JPG

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#161]
Ensure level Cover/Screenshots should only allow JPG uploads to save space/traffic.

**Comment by rr-** [comment]
I'll address this IF this becomes an issue by converting uploaded PNGs to JPEGs.

**Comment by Klona13** [comment]
It is kind of an issue already.

People usually play above 720p nowadays which will always result in images higher than 1MB. This makes uploading pretty annoying when you have to make it a JPG anyway. Additionally, I don't want people to upload 480p PNGs... 1080p JPGs are going to look better.

Ultimately, using JPGs entirely eliminates any kind of issue.

**Comment by Klona13** [comment]
Not sure why this is happening to images 2 and 3, even though they are smaller in size than image 4.
![image](https://user-images.githubusercontent.com/93257509/162539257-6f5e7674-f579-43cd-8070-16e944edad34.png)

But after submitting they still show up fine:
![image](https://user-images.githubusercontent.com/93257509/162539884-e81e4291-dc01-4780-b3f7-eac5081b7536.png)

There's another issue here, the cover image and image 1 were not converted to jpg. They are still PNGs, but they were small already. A JPG conversion should make them much lighter without losing quality.

**Comment by rr-** [comment]
Can you share the failed image in question?

**Comment by rr-** [comment]
Some of the images were already JPEGs.
I can't reproduce the issue with the issue with the missing images. Can you post a video of it and the images you're using?

**Comment by Klona13** [comment]
I sent the info on discord.
