### ISSUE TITLE
Download link to the folder is not preserved when updating the level

### ISSUE THREAD

**Issue by Kubsy** [rr-/trcustoms#180]
Whenever I would like to update the level (to change something in details for example: story/  or screenshots), the download link is not preserved and you have to choose the folder again.

![image](https://user-images.githubusercontent.com/80340234/160276797-8b6541dc-ef92-48d2-8ba0-cce847a33972.png)

**Comment by rr-** [comment]
What folder?

**Comment by Klona13** [comment]
> Whenever I would like to update the level (to change something in details for example: story/ or screenshots), the download link is not preserved and you have to choose the folder again.
> 
> ![image](https://user-images.githubusercontent.com/80340234/160276797-8b6541dc-ef92-48d2-8ba0-cce847a33972.png)

Please give steps to reproduce this @Kubsy

**Comment by Kubsy** [comment]
So go to your level then click edit and go down to level file.

**Comment by Kubsy** [comment]
> 

Level folder

**Comment by Klona13** [comment]
I think you are confused, because the level file is still there and doesn't disappear.
This field is for updating your level if you want.

@rr- We could clarify it by renaming the section.

## File version update
Update file:
> Drop the update file here, or click on this box.

**Comment by Kubsy** [comment]
Oh ok yeah

**Comment by Kubsy** [comment]
I wasn't sure if by the level file you have to upload the whole folder again

**Comment by Klona13** [comment]
> ## File version update
> Update file:
> 
[ Drop the update file here, or click on this box. ]

Please make sure the * is removed from the upload widget in the level edit form cause it isn't mandatory to update the file itself.

**Comment by rr-** [comment]
>[ Drop the update file here, or click on this box. ]

I won't customize this, too much spaghetti.
I'll remove the asterisk.

**Comment by Klona13** [comment]
Ok acceptable

**Comment by Klona13** [comment]
@Kubsy 
Can you please compare the upload page and the level edit page?

**Comment by Kubsy** [comment]
Upload page:
![image](https://user-images.githubusercontent.com/80340234/160353761-dbc36784-be15-4b4a-ba4c-44a5137e15ab.png)

While editing the level 
![image](https://user-images.githubusercontent.com/80340234/160353881-560add60-c076-44ed-8172-fd49c27e0a62.png)

hope that helps
