### ISSUE TITLE
Review Errors - making review

### ISSUE THREAD

**Issue by Kubsy** [rr-/trcustoms#183]
When only ticking the slightly disagree combobox for the last question, the "please review errors show up" however it doesn't point to where fix the errors. 

for other comboboxes it points out where to correct the errors

![image](https://user-images.githubusercontent.com/80340234/160368571-a74b4068-8728-4a92-92ef-cf863f943912.png)
![image](https://user-images.githubusercontent.com/80340234/160368687-4909da03-01b9-421e-b9ed-430d64bc499d.png)
![image](https://user-images.githubusercontent.com/80340234/160368719-6b3a3203-45e5-43a8-ba7e-e4d3cd28b96f.png)

This might be the case for other questions, haven't tested yet.

**Comment by rr-** [comment]
@Klona13 are you able to reproduce this issue?

**Comment by Klona13** [comment]
It happens to all questions except for the first one when selecting an answer then submitting. It would stop pointing out where the error is UNTIL you select another answer, which will start showing the correct errors.

Only Q15 is answered:
![image](https://user-images.githubusercontent.com/93257509/160878193-8d8fe949-2a80-4f98-a164-489bac90f9ec.png)

Q15 answer changed, other Qs no answer:
![image](https://user-images.githubusercontent.com/93257509/160878207-63897b51-f0cd-4964-ba87-44d4ccc3fb73.png)
