### ISSUE TITLE
Wording Update - Mod Guide sections

### ISSUE THREAD

**Issue by MatieTR** [rr-/trcustoms#188]
Nothing major at all, just some nitpicking:

### Introduction
As a moderator, you have the ability to ~~give~~ provide and revoke access

### Moderate Tab
You can ~~also~~ access the "Moderate" tab from the navigation bar. It includes all action logs of new additions or changes ~~in~~ on the website. You may ~~also~~ search for specific action logs using the search filter, which also has a button to a list with all users.

_(This paragraph has 3 "alsos" in it.)_

### Profiles
User profiles that contain anything that goes against the Terms and Conditions must **_be_** edited immediately to ~~omit~~ remove the ~~information~~ content.  Contact the administrator about the incident. _(+ add: With proof provided? Unless edit history is kept and proof of the incident isn't needed. It's good to have proof of the original content in cases of dispute.)_

**Comment by Klona13** [comment]
Please replace these 3 sections.

## Introduction
As a moderator, you have the ability to grant and revoke access to certain parts of the website. Additionally, you may edit certain pages that go against the Terms and Conditions. This document aims to guide you on how you can help manage the website.

## Moderate Tab
The "Moderate" tab can be accessed from the navigation bar, it includes logs of actions ( such as new additions or changes) done on the website. Some of these logs will be labelled "Requires action", which means a moderator has to approve or reject this change or addition. You may search for specific action logs using the search filter, which also has a button to a list with all users.

## Profiles
User profiles that have content that goes against the Terms and Conditions must be edited immediately, and the content in question must be removed. Contact the administrator about the incident.

**Comment by Klona13** [comment]
Include this section between tags and banning members.

## Banned Content
Banned content is defined as content that should be IMMEDIATELY removed on sight. If you don't have the capability to remove this content, contact the administrator. 
Examples:
1. Realistic-looking gore
2. Nudity
3. Sexual acts
4. Explicit hardcore pornography 
5. Explicit sexualization of minors

Points 1, 2, and 3 are allowed in levels, but cannot be displayed to the public on the level page. If they are present on the level page, the level must be rejected and the reason provided must mention the inclusion of appropriate tags (Nudity, Gore, Sexual Acts).
