### ISSUE TITLE
Prevent mods from banning self or site admin

### ISSUE THREAD

**Issue by MatieTR** [rr-/trcustoms#189]
Anything can happen, you never know. Hope this community will never be that toxic.

The deactivate and ban buttons can be tempting (:

**Comment by Klona13** [comment]
Perhaps just remove the deactivate and ban buttons for the super user.

**Comment by Klona13** [comment]
I was still able to deactivate and reject the super user. It has been purged again.

(send help again0

**Comment by rr-** [comment]
Restored the user

**Comment by rr-** [comment]
Should be fixed now
