### ISSUE TITLE
Prevent mods from editing crucial personal info

### ISSUE THREAD

**Issue by MatieTR** [rr-/trcustoms#190]
Only admins should be able to reset a user's password or change their email address. These shouldn't be editable by mods and should be greyed out/uninteractable.
(Edit: I can see now that the old password is needed to change that, so that part is fine. Mails need confirmation so that seems also seems fair, although would warrant some questions if someone did try)

**Comment by Klona13** [comment]
I agree.
All that is needed to fix this is require the password to be written to be able to update the email.

**Comment by rr-** [comment]
Too many things discussed at once. File these in relevant issues. Currently this ticket is not actionable.
