### ISSUE TITLE
Author names disappeared

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#198]
Author names disappeared from the new levels by testers, the non-scraped levels.
I noticed this yesterday on the 30th, and none of them were updated that day.

Did something break while deploying? Or is this just a one-time thing?

(I readded Raildex here cause he made this, it was "Unknown")
![image](https://user-images.githubusercontent.com/93257509/161103493-4bcaa68e-66fe-4fe5-9c80-1733c46f443d.png)

**Comment by rr-** [comment]
I think one time, can't reproduce it.
