### ISSUE TITLE
No HTTPS redirect

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#204]
Many people try to access the site by just typing "trcustoms.org" and it directs them to http instead which shows this:
![image](https://user-images.githubusercontent.com/93257509/161393286-2f309dac-9155-4ab4-b2df-9fb43b6b0a9c.png)

People will think the site doesn't work like this. Could we have it redirect to https?

**Comment by rr-** [comment]
Requires testing on incognito due to caching.
Requires manual entry of `http://trcustoms.org` into the addressbar.

**Comment by Klona13** [comment]
Works without incognito if you shift+F5.
Closing.
