### ISSUE TITLE
Safari browser - Site doesn't load

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#205]
Someone reported that the website doesn't load on Safari.

**Comment by rr-** [comment]
This ticket is nonactionable. At minimum it requires

Browser version
Platform
Platform version
Console logs (f12 + refresh)

**Comment by Klona13** [comment]
It seems like there's an inconsistency across devices that use Safari.

I tested it on an iPhone and a Mac laptop and both loaded the main page. But they didn't load the news section or the level page.

As this ticket is nonactionable, I will be closing it since there are alternatives such as using a different browser.

If there was a simple fix or if someone is able to provide one, then this issue can be reopened.
