### ISSUE TITLE
Level list - Sorting by Last Updated

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#209]
Add "Last updated" in the sorting dropdown list here:
![image](https://user-images.githubusercontent.com/93257509/161439979-592d4fcf-efef-4777-aab4-b71ef605bd5d.png)

**Comment by Klona13** [comment]
It should show the last updated level in the list.
Right now it shows it the other way around with the latest updated level being the last on the list.

**Comment by rr-** [comment]
I thought I did it in the right direction, because the last updated level on my local database was quite recent, but after this reopen, I realized all of my testing levels were updated on the same day :D
