### ISSUE TITLE
Walkthroughs

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#210]
# 1. On the Level Page 
## Sidebar Button & Modal
On the level page sidebar.

When you click on it, a modal box in the middle appears:
![image](https://user-images.githubusercontent.com/93257509/163389721-a4884bd5-36c3-47a3-83cc-769b752d27a5.png)

If there are no walkthroughs listed, the table just says "No walkthrough has been submitted yet."
If the list has more than 10 walkthroughs, it's separated into pages in the modal.

## Actions

Clicking on the "Read guide" takes you to the walkthrough viewer where you can read it. "Watch video" takes you straight to the video link/playlist.

Clicking on Create text guide button takes you to the Walkthrough Editor so you can write a new walkthrough.

Walkthroughs that aren't assigned to a user are unclickable (see below).

Mods must approve these walkthroughs by clicking on "Approve" or "Reject" on the list on the modal (Approve button disappears after using it, and then only Reject remains). You still need to enter a reason for Rejection for the email and log.

The super user can see an extra button in Mod Actions: Delete. The user who submitted the walkthrough and can see the Edit button for their own walkthroughs only. Mods can see the Edit button for all.

Clicking Edit for a text guide would take me to the Walkthrough Editor.
Clicking Edit for a video guide will simply update the link. If no link is entered on the field below, it will be highlighted by an error saying "Insert a video/playlist link". (If it's possible to make the video guides have a button called "update" instead of "edit" that would be better).

## Name import
As some walkthrough writers never had a profile on TRLE.net, the name will be imported from "Walkthrough by xxx" in the actual text as it's the only consistency I could find.

E.g. Phil uses his full name in the walkthrough. So it will show his fullname instead.
How to possibly do this:
1. If the imported name matches a username, a [owner-username] is filled and shows up under "Submitted by"
2. If there is no match, it is stored under [owner-altName] which will show up in "Submitted by"
3. [owner-username] takes priority over the [owner-altName] and clears the latter to prevent 2 names from showing up.

# 2. Walkthrough Editor page
## Markdown Textbox
A regular markdown textbox, but it spans the entire page vertically. It has the following text in it by default:
```
# Level Walkthrough
## Level 1
Example text.

## Level 2
Example text.
```

The reasoning for this is in the following section:

## Sidebar
Sidebar has "Chapters" section with one chapter in it. Users can add more chapters by creating more H2 in the walkthrough's textbox. The textbox already has example text in it to lead on the user.

Above the "Chapters" section, there is 3 buttons in this order:
- "Save Draft": Saves all textboxes on the page
- "Finalize/Submit": Submits for approval (users can still edit the page, this just informs mods it's ready to be looked at with "Action Required". After pressing it, this button disappears forever. (Users can still edit the walkthrough normally)

# 3. Audit Log
- Walkthrough - Created
When first created
- Walkthrough - Submitted (Action Required)
When users click on finalize/submit
- Walkthrough - Updated
When edited at any point by the user
- Walkthrough - Removed
When deleted by the superuser
- Walkthrough - Approved
Approved by Mods
- Walkthrough - Rejected (Reason: X)
Rejected by Mods

# 4. Counter
A walkthrough counter shows in your profile for the number of walkthroughs linked to your account.

# 5. Homepage statistics
The bar is based on the Z% of Missing, text guide, and video guide bar sections.

## No selection
X= [number of all walkthroughs] Total
Y = [number of levels with at least 1 guide]
Z% = Y ÷ [Total levels]
![image](https://user-images.githubusercontent.com/93257509/161823606-d970c3f2-94bc-4ae1-a592-ad87330db7ac.png)

## Hovering Missing
X= None
Y = [number of levels with no guide]
Z% = Y ÷ [Total levels]
![image](https://user-images.githubusercontent.com/93257509/161824950-81c1cefe-4511-4a3a-b3fa-eb57aab4a30f.png)

## Hover Text Guide
X= [total number] Text Guides
Y = [number of levels with at least 1 text guide]
Z% = Y ÷ [Total levels]
![image](https://user-images.githubusercontent.com/93257509/161823725-a63f701c-9462-4994-a8a6-54b9547cf8dd.png)

## Hover Video Guide
X= [total number] Video Guides
Y = [number of levels with at least 1 video guide]
Z% = Y ÷ [Total levels]
![image](https://user-images.githubusercontent.com/93257509/161823925-932c42df-1fb7-46cc-8f9e-c84c030da785.png)

# 6. Walkthrough list in profile
In the user's profile, clicking on the walkthrough count takes you to the walkthrough list page. It shows a table of walkthroughs you submitted and their status. Other users would just see approved walkthroughs without the status column.

| Level             | Guide Type |Submitted On | Last Updated | Status    |
|-------------------|------------|----------|--------------|--------------|
| Tomb Raider: blah | Text       | date         | date         | Rejected |
| Crazy Adventure   | Video      | date         | date         | Pending  |
| HeeHee            | Video      | date         | date         | Approved |

Clicking on level name would take you to that level's page. You have to go to the level's page and see the walkthrough from there to edit it.

**Comment by rr-** [comment]
There are too many modals. Modals are in general very poor UX. Can you reduce their amount? Can we put a section under Level description for the walkthroughs?

**Comment by Klona13** [comment]
1. I've been meaning to rewrite that modal into one single modal. I'll edit it now.
2. This could be solved by adding an "Edit" button for people who have privilege to see the Editor. Clicking normally on a walkthrough would be the view mode. The Finalize/Submit is for the FIRST submission, like the page isn't ready yet usually so people may spend days/weeks working on a page before they're ready to finalize.
3. OH OK we can go with the WYSIWYG editor way.
4. Ah so you mean separating the chapters by H2? I thought about this, but I feel like it's a little risky to have thousands of words hinging on a single text box. Recipe for bad UX in case an accident happens.
5. It could be automatically converted to markdown. We don't need to do the coloring bit, unless you can like automatically process it to find words like medipack/secret/ammo/dog/enemy/baddy and just automatically color it. It could be done manually also even if it takes a while, it's worth restoring these guides. You could delegate this to the community in a separate ticket and provide the scrapped walkthroughs maybe?
6. The bar is just an example, its size is based on the Z%.

**Comment by Klona13** [comment]
@rr- Updated large sections for clarity. Please LMK if something is off or weird or just undoable.

**Comment by rr-** [comment]
4. Ah so you mean separating the chapters by H2? I thought about this, but I feel like it's a little risky to have thousands of words hinging on a single text box. Recipe for bad UX in case an accident happens.

The solution is to save drafts to local storage periodically

**Comment by Klona13** [comment]
> 4. Ah so you mean separating the chapters by H2? I thought about this, but I feel like it's a little risky to have thousands of words hinging on a single text box. Recipe for bad UX in case an accident happens.
> 
> The solution is to save drafts to local storage periodically

How would this work exactly?

**Comment by rr-** [comment]
Every 5 s would save the review into the local storage.
Upon refreshing instead of presenting the user with a blank textarea, it would load the remembered text.
Submitting the form would clear the form.

**Comment by Klona13** [comment]
Ok that works.

**Comment by Klona13** [comment]
Gonna compile everything here over the next day.
first up:
It would be nice if the video wasn't pushed to the side like this if there are no buttons here.
![image](https://user-images.githubusercontent.com/93257509/166847686-da651b46-05ba-4f72-bb38-6afbb9bad523.png)

**Comment by Klona13** [comment]
There seems to be an issue.
If I submit a video walkthrough, and then try to create a text based walkthrough, it takes me to edit the video link instead.

**Comment by Klona13** [comment]
I created a walkthrough for postmortem and saved my draft, but it was never actually created.
It seems that the creation function is tied to "submit for approval" instead of "save draft".
The purpose of this function is to allow people to continue this later if they weren't done writing/formatting very large walkthroughs.
![image](https://user-images.githubusercontent.com/93257509/166848596-3fba2bef-dee3-4bbe-8585-53258e9a8722.png)
![image](https://user-images.githubusercontent.com/93257509/166848619-14ad2385-cf69-4b8d-a1cb-9c8da40db70f.png)
![image](https://user-images.githubusercontent.com/93257509/166848635-8b9bdb88-d893-41cc-994e-e756483497e6.png)

**Comment by Klona13** [comment]
From another account with no special privs, I tried to create a text walkthrough, but I got error 403.
This happens for levels WITH and WITHOUT text walkthroughs.

Right now I can only make a text walkthrough with Super user.

**Comment by rr-** [comment]
@Klona13 I thought I had freedom with how to tackle the drafts. Since you want me to show the drafts in the user listing it means they need to be saved into the DB. This requires more thinking.

1. What exactly happens if I save a draft (I assume I don't create an audit log)
2. What exactly happens if I finalize a draft (I assume this does create an audit log)
3. What exactly happens if I finalize a non-draft (you wanted the edits to be still possible, do I change the button label for published drafts? what about audit logs?)
4. The restore draft button should be removed, is that right?
5. You're OK with walkthrough drafts indefinitely sitting in the DB if the author never pressed the finalize button, yes?
    - This includes hosting all the attachments for free for them.
6. Who exactly sees the drafts in the user profile? Just the owner?
7. Drafts aren't shown in the level page modal, is that correct?

**Comment by Klona13** [comment]
Don't get me wrong, I'm happy with how it works. However, I thought I explained that people need to be able to go back to the edit page and work on it even if it's not ready for submitting.

1. Saving a draft is like "Submit for Approval", except that the only thing it doesn't do is notify mods. It should CREATE the walkthrough, just not publish it. It still has the Approve/Reject/Delete buttons in it, but the audit log shows walkthrough was Created, but no action requirement.
2. Adds "Action requirement" so mods know it's time to look.
3. Action requirement shows up only one time, so only the first approval is necessary.
4. I suppose with this change, it's not needed anymore and it overcomplicates things.
5. Unused drafts should disappear in 21 days (3 weeks). Maybe a warning should be present on the edit page:
"(i) Keep backups saved on your machine as **unpublished drafts** will be deleted after 1 week if not updated/submitted.
Users cannot see your walkthrough until your draft is submitted and approved."
This will automatically delete drafts that overstayed their welcome and delete any unused attachment afterwards.
6. Author and mods
7. No, they aren't.
8. Links are always finalized and not drafts, so it should always become "False".

**Comment by Klona13** [comment]
On top of that, Saving and restoring drafts is buggy.
If I save a draft from walkthrough A, and then go to walkthrough B and click restore, it will restore the draft from walkthrough A.

**Comment by Klona13** [comment]
Round this off to the nearest tenth:
![image](https://user-images.githubusercontent.com/93257509/166955678-8cc1a4ad-9021-4b67-889c-80aca450b827.png)

For consistency as the others are rounded the same way:
![image](https://user-images.githubusercontent.com/93257509/166956010-b829ed91-62d0-498e-a94e-52a768285307.png)

The numbers will look like this:
![image](https://user-images.githubusercontent.com/93257509/166955984-3d41ace6-ce1d-419a-8090-efa26e391214.png)

**Comment by Klona13** [comment]
If users aren't signed in, they can't see the walkthrough button.
Everyone should be able to see available walkthroughs, but you can't add new if you aren't registered naturally.

**Comment by rr-** [comment]
>It would be nice if the video wasn't pushed to the side like this if there are no buttons here.

Done, now it's a horizontal strip

>If I submit a video walkthrough and then try to create a text based walkthrough, it takes me to edit the video link instead.
>
>What should happen is one of the two:
>
>If I don't have a text based walkthrough, it should let me make one. (Even if I have a video walkthrough submitted)
>If I already have a text based walkthrough, it should warn me saying I already made a walkthrough of this type.

Fixed, but I don't display an alert, I just take directly to the edit page

>I created a walkthrough for postmortem and saved my draft, but it was never actually created.
>It seems that the creation function is tied to "submit for approval" instead of "save draft".
The purpose of this function is to allow people to continue this later if they weren't done writing/formatting very large walkthroughs.

Drafts will be reworked separately

>From another account with no special privs, I tried to create a text walkthrough, but I got error 403.
>This happens for levels WITH and WITHOUT text walkthroughs.
>Right now I can only make a text walkthrough with Super user.

Fixed

>Draft instructions

Drafts will be reworked separately

>On top of that, Saving and restoring drafts is buggy.
>If I save a draft from walkthrough A, and then go to walkthrough B and click restore, it will restore the draft from walkthrough A.
>Now I think people should backup on their own.

That was intentional shortcut on my part. Either way,
Drafts will be reworked separately

>Round this off to the nearest tenth:

Done

>If users aren't signed in, they can't see the walkthrough button.
>Everyone should be able to see available walkthroughs, but you can't add new if you aren't registered naturally.

Fixed

**Comment by rr-** [comment]
Drafts finished; together with draft autoremoval.
The only change is that like with the unapproved levels, the mods won't see drafts via the user profile, only the moderation panel.

**Comment by Klona13** [comment]
Slight change to the end of the email. Currently it says:
![image](https://user-images.githubusercontent.com/93257509/167046588-e47571f1-5e0e-478c-afa2-06010e1336aa.png)

But it links to the walkthrough page.

Maybe it should be "View your walkthrough page here."

**Comment by rr-** [comment]
Fixed

**Comment by Klona13** [comment]
For testing purposes:
![image](https://user-images.githubusercontent.com/93257509/167232908-a392d2ae-9eb3-4e13-91eb-078ce5ca2367.png)

Waiting now

**Comment by Klona13** [comment]
I updated the circled walkthrough.
The rest is as expected:
![image](https://user-images.githubusercontent.com/93257509/168328213-84fbdfc0-c52a-402f-88a8-249c5c71a5a1.png)
