### ISSUE TITLE
line spacing only works on some conditions 

### ISSUE THREAD

**Issue by Kubsy** [rr-/trcustoms#212]
If I want a text to appear immediately like this:
![image](https://user-images.githubusercontent.com/80340234/161598206-c29bb4b9-3dbf-4f9a-b9c3-43ce1c608ae8.png)
then it won;t work as everything gets formatted to one line:
![image](https://user-images.githubusercontent.com/80340234/161598250-1b341555-336b-4b83-98c2-10acc9c10b33.png)

this only works if you leave 1 line blank like this: 
![image](https://user-images.githubusercontent.com/80340234/161598311-8e6692a5-d2fb-498a-845a-a314f57410f6.png)
![image](https://user-images.githubusercontent.com/80340234/161598329-5c9c16d4-fb8b-4dc7-9216-6fb49ea51f2a.png)

Not too sure if it's intended or a bug but reporting it just in case.

**Comment by rr-** [comment]
@Klona13 can you follow up with the markdown tickets i asked you for earlier?

**Comment by Klona13** [comment]
> If I want a text to appear immediately like this: ![image](https://user-images.githubusercontent.com/80340234/161598206-c29bb4b9-3dbf-4f9a-b9c3-43ce1c608ae8.png) then it won;t work as everything gets formatted to one line: ![image](https://user-images.githubusercontent.com/80340234/161598250-1b341555-336b-4b83-98c2-10acc9c10b33.png)
> 
> this only works if you leave 1 line blank like this: ![image](https://user-images.githubusercontent.com/80340234/161598311-8e6692a5-d2fb-498a-845a-a314f57410f6.png) ![image](https://user-images.githubusercontent.com/80340234/161598329-5c9c16d4-fb8b-4dc7-9216-6fb49ea51f2a.png)
> 
> Not too sure if it's intended or a bug but reporting it just in case.

That's normal markdown. The spacing between two paragraph just happens to be the same size as the double linebreak, which markdown language requires to do a linebreak.

**Comment by rr-** [comment]
@Klona13 I can make it work with normal line breaks too along with adding support for custom tags from #214 but I'm not sure if that's something you'd want?
