### ISSUE TITLE
Text Formatting Guide

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#214]
This page is accessed from the ? icon in the right of the WYSIWYG.
Next to textboxes, there's a Formatting Guide button that opens a new tab.
The page has side by side views of syntax and the result preview. The sidebar is like a navigation menu.

## Headings
```
# Heading size 1
## Heading size 2
### Heading size 3
```

## Text styles
```
**Bold text**
_italicized text_
~Strikethrough text~
```

## Text coloring
```
[p]Blue for Pickups[/p]
[s]Gold for Secrets[/s]
[t]Orange for Traps[/t]
[e]Red for Enemies[/e]
[o]Green for Objects of Interest or Interactibles[/o]
```

## Links
```
[example website title](https://www.example.com)

![Lara wink image](https://i.imgur.com/ZD0KMrl.png)
```

## Blockquote
```
> This is a quote in a block.

> Another quote...
>
> in one box with a linebreak
```

## Horizontal line
```
Text before line.

---
Text after line.
```

## Lists
```
- [x] Write the press release
- [ ] Update the website
- [ ] Contact the media

1. First item
2. Second item
3. Third item

- First item
- Second item
- Third item
```

## Tables:
```
| Object Info | Level 1 | Level 2 | Level 3 |
| ----- | ----- | ----- | ----- |
| Secrets | 5 | 2 | 3 |
| Enemies | 23 | 33 | 8 |
| Pickups | 28 | 14 | 19 |
```

## Footnotes
```
Here's a sentence with a footnote. [^1]

[^1]: This is the footnote.
```

**Comment by rr-** [comment]
@Klona13 new tab or a modal?

**Comment by Klona13** [comment]
Tab because maybe some people want to use it as reference side by side.

**Comment by Klona13** [comment]
It would look nicer if each section was in its own textbox

**Comment by rr-** [comment]
What does that mean?

**Comment by rr-** [comment]
Never mind, I think I figured it out :)

**Comment by Klona13** [comment]
Doesn't look right on mobile here.
![image](https://user-images.githubusercontent.com/93257509/164979801-f1e8cb5f-4576-400e-b9c4-2bd1b1365656.png)
![image](https://user-images.githubusercontent.com/93257509/164979796-aa6f0777-7e1a-4543-acb6-4f9b83273ab9.png)
