### ISSUE TITLE
Level List - Last Updated Date Stuck

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#217]
The "Last updated" date on the level list is stuck.

**Comment by rr-** [comment]
This tells me exactly nothing.

**Comment by Klona13** [comment]
The date on the level list doesn't change.
![image](https://user-images.githubusercontent.com/93257509/162000473-2b5f5488-8f4b-4c5d-b929-91053898a47c.png)

The real date is on the level page.
![image](https://user-images.githubusercontent.com/93257509/162000538-3ed4a244-06cb-4d36-878e-a68f772fc13d.png)
