### ISSUE TITLE
Add report content button

### ISSUE THREAD

**Issue by MatieTR** [rr-/TRCustoms#219]
Feature request for the future - add a 'Report' button to allow users to report content that violates T&C. Allow superuser (and mods?) to see what was reported and review reported content. Allow admin/mods to close each case with a note to user as to how their report was addressed or why it was declined.

**Comment by Klona13** [comment]
Case system is too complicated for a fansite like this. I'd opt for a simple system where a report would just send an email to the admin.

**Comment by Klona13** [comment]
When users click on the report button, the modal pops up to ask for the reason. When they submit, it shows up in the log too with the reason. Also Action Required.

The reported user/level page is the object. 

The following buttons also clear the action requirement.
Level page: False report / Reject
Users: False report / Deactivate or Ban

**Comment by Klona13** [comment]
I don't know if a reporting feature is necessary.
It adds so many steps in between when you can just contact someone on discord/forum/twitter.
You can just:
1. see the bad content
2. @ someone
