### ISSUE TITLE
Profile - Website

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#222]
Users can add their website as a button in the sidebar (like in the level page).
It can be added by editing the profile.

**Comment by Klona13** [comment]
Can it open a new tab instead of just going there?

**Comment by rr-** [comment]
What?

https://tmp.sakuya.pl/f/2022-04-14_11.04.38.webm

**Comment by Klona13** [comment]
Maybe my phone was being weird 
it works now
