### ISSUE TITLE
[Production] Real release date for levels that were restored

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#223]
3392 -	2008.07.23.
3393 -	2008.09.16
3394 -	2009.05.31
3395 -	2012.06.01
3396 -	2012.06.22
3397 -	2012.11.26
3398 -	2013.11.10
3399 -	2013.11.19
3400 -	2013.11.25
3401 -	2014.02.16
3402 -	2014.02.25

**Comment by rr-** [comment]
Done
