### ISSUE TITLE
Level List - Sort by Least reviewed

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#224]
Sort by least reviewed. (add it under Last updated)
No need for most reviewed cause they already have too much, and the dropdown list will be too long.

**Comment by Klona13** [comment]
@rr- This should be communitcated better on the level list itself, as people won't know how many reviews it has until clicking.
Reviews to Rating
and mention the number of reviews in a bracket.
![image](https://user-images.githubusercontent.com/93257509/162496448-e43d77f9-f9c1-46f3-80a8-966c4bbb5c13.png)

**Comment by rr-** [comment]
New ticket

**Comment by rr-** [comment]
Added, but this should have been a new ticket
