### ISSUE TITLE
Level list filter minimizing

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#225]
Allow minimizing of all sections.

And reorder like this:
Genre
Tags
Engine
Date (#302)
Ratings (#233)
Duration (#234)
Difficulty (#235)
They have the up/down double arrows for minimizing/maximizing action (or can use + -):
https://heroicons.dev/?query=double+

We could settle for a design similar to
![image](https://user-images.githubusercontent.com/93257509/194759839-02afcbd5-f141-4254-a912-d7516b4919ee.png)

The design for these would be similar to:
![image](https://user-images.githubusercontent.com/93257509/194759936-936e1665-1941-45a7-98f8-ea9ac359ecb9.png)
But take up the width of the side bar with the min/max button on the right.

**Comment by Klona13** [comment]
wdyt of something like this?
![image](https://user-images.githubusercontent.com/93257509/196000169-4f0c0626-664b-4b60-b0ed-7db37b46971e.png)

**Comment by rr-** [comment]
I don't think we should remove the "(clear)" reset button for each section tho?

**Comment by Klona13** [comment]
Sacrificing some usability to make it less crowded. There's still the main reset button.

**Comment by Klona13** [comment]
Could you please make it so that it's clicked on from anywhere on the box, and not specifically the arrow?
![image](https://user-images.githubusercontent.com/93257509/210156488-80593d8b-4852-4f03-9100-5a577796e9c0.png)
