### ISSUE TITLE
Edit Form - Image Size Limit

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#229]
The size limit should be 10 MB.
Currently it works uploading form, but doesn't anymore on the edit form.

**Comment by rr-** [comment]
Can't reproduce, can you post a video?

**Comment by Klona13** [comment]
@rr- 
You can upload ~10MB PNGs
But not JPEGs
![image](https://user-images.githubusercontent.com/93257509/162518242-2780ffc1-f9eb-459a-b144-3a938ba2b7ec.png)
![image](https://user-images.githubusercontent.com/93257509/162518296-73183c9c-3e95-48b4-8f34-80bd9917c218.png)

**Comment by rr-** [comment]
You told me to do it this way on Discord yourself

**Comment by Klona13** [comment]
https://en.wikipedia.org/wiki/Alzheimer%27s_disease
