### ISSUE TITLE
User profile clarity

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#238]
2 sections within the sidebar, wdyt?

## User info
Join date:
Country:

## User submissions
Levels:
Reviews:
Walkthroughs:

**Comment by rr-** [comment]
That's not a lot, just 5 data points.

**Comment by Klona13** [comment]
@rr- 
Better?
![image](https://user-images.githubusercontent.com/93257509/163041012-2babc712-b386-42ad-ae49-3597ca74222d.png)

**Comment by rr-** [comment]
Yeah looks good

**Comment by Klona13** [comment]
This area should be under user info
![image](https://user-images.githubusercontent.com/93257509/163171155-43fdedcc-531b-4c19-9944-ad43ebd911d6.png)
