### ISSUE TITLE
Trcustoms: problem on Firefox version 99.01

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#241]
Die Basis reported that when he loads the website on Firefox version 99.01, only a picture loads, nothing else. Even after deleting cookies the website still loads the picture only. Most probably it's Firefox messing things up.

![image](https://user-images.githubusercontent.com/80340234/163188099-00d8be09-cc73-4805-a651-26c13c90a9b8.png)
![image](https://user-images.githubusercontent.com/80340234/163189190-d9e6fa45-84a4-4100-a5b6-6b99d3786449.png)

**Comment by rr-** [comment]
Sorry but without a screenshot of the console this report is not very helpful.

**Comment by Kubsy** [comment]
Hmm ok, I'll try to tell Die Basis to access the console and screenshot

**Comment by Kubsy** [comment]
![image](https://user-images.githubusercontent.com/80340234/163238505-40787593-2caf-47cf-8a43-494eea3c6a07.png)
Die basis provided me with this, it's in german but it says ".css was not loaded because mime-type "text/html" is not "text/css"

hope it's useful
@rr-

**Comment by rr-** [comment]
Can they ctrl+f5 the page?

**Comment by Kubsy** [comment]
ok so Die Basis said that pressing ctrl+F5 brought the website to "life" (I guess it works for them) so I'll close it and reopen if necessary.
