### ISSUE TITLE
WYSIWYG support for the Markdown editor

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#246]
Add buttons to do some common things:

- Header
- Bold
- Italics
- Strikethrough
- Link
- Quote
- Code
- Numbered list
- Bulleted list

**Comment by Kubsy** [comment]
May I ask: what is code?

**Comment by rr-** [comment]
@Kubsy 

```markdown
`inline code`
```

Results in: `inline code`

<pre>
```
dedicated code block
```
</pre>

Results in:

```
dedicated code block
```

**Comment by Klona13** [comment]
The useful things are in #214

**Comment by Kubsy** [comment]
> @Kubsy
> 
> ```gfm
> `inline code`
> ```
> 
> Results in: `inline code`
> 
> ```
> dedicated code block
> ```
> Results in:
> 
> ```
> dedicated code block
> ```
> 
> Come to think of it I don't think it's all that useful for TRC.

Hmm I see, thank you.

Hmm, yeah I don't know if it's useful as Klona says. maybe if someone wants to show off their coding skills then maybe ;p
