### ISSUE TITLE
Attachment support for the Markdown editor

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#247]
Add a button that lets people paste an image.

Need to somehow link the image to the text so that it doesn't get auto-purged.

**Comment by rr-** [comment]
@Klona13 please test the regular file upload widget as well for regressions, since I touched parts of its code as well.

**Comment by Klona13** [comment]
I am testing it now.
Also, I think we should probably only allow images.

**Comment by rr-** [comment]
>Also, I think we should probably only allow images.

What about people attaching save files and the like to walkthroughs to help mitigate softlocks?

>From what you said on discord, this affects all attachments. Does this mean any "uploaded file"?

Yes. Just test it for regressions if it's still working – level covers, level screenshots, reordering level screenshots, removing, adding level screenshots; level file; user picture. Wrong file, good file, too big image, just right image etc.

**Comment by Klona13** [comment]
I'll be posting findings here as I test...


File attachments are shown the same way as images, which makes them unclickable by default. It should be without the "!" and I think it should say [Download] instead of being empty [],
![image](https://user-images.githubusercontent.com/93257509/165249988-608c49c4-cb46-4482-aa0d-8dc3ea63d64c.png)

**Comment by Klona13** [comment]
Testing. Highlighted files are linked to level page, profile, review.
Non-highlighted files should be removed as they are not linked. I just uploaded them but I didn't save the page so they aren't linked.
![image](https://user-images.githubusercontent.com/93257509/165256392-37bd04b2-c463-4587-abf9-f5cc9f550254.png)

**Comment by rr-** [comment]
@Klona13 fixed the first issue.
The second report is invalid. The files have to be older than 24 h otherwise they might get deleted before the user even has the chance of saving the form.

**Comment by Klona13** [comment]
Today... still testing.
Removed 221's link.
Waiting again.
![image](https://user-images.githubusercontent.com/93257509/165556137-0f97a61a-aa4c-4392-a71e-313d0c005e8c.png)

**Comment by Klona13** [comment]
Is this normal?
221 disappeared before the set time.
![image](https://user-images.githubusercontent.com/93257509/165742840-e6ec455d-7ce0-476c-b603-dfa33aaa128c.png)
![image](https://user-images.githubusercontent.com/93257509/165742880-be738024-c6fa-4d48-87f4-dbce4699943b.png)
