### ISSUE TITLE
Download counter does not increment

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#251]
I have been noticing that the download counter for my ORC demo has not been increasing, it is stuck at 39 downloads for the past few days now. Same with Denis' and Sabatu's level.

**Comment by rr-** [comment]
Isn't this because people do not download them?
The counter works fine on staging and localhost.

**Comment by rr-** [comment]
@Klona13

**Comment by Kubsy** [comment]
Caesum said he downloaded the level and the counter didn't increase.

**Comment by rr-** [comment]
@Kubsy OK I found the problem. I'll fix it soon, but for now know that the downloads are still counted so your stats are not gone.

**Comment by rr-** [comment]
Fixed on production :)
