### ISSUE TITLE
Add side-by-side view for Markdown preview

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#259]
Should be configurable for the users who don't like the distracting interactivity to revert back to tabs.

**Comment by Klona13** [comment]
This could be in the Settings tab to enable or disable this, right?

**Comment by Klona13** [comment]
I think the code change caused some issue?
![image](https://user-images.githubusercontent.com/93257509/165770152-4584e647-cba0-44a1-8d78-2a9eba38e29e.png)

![image](https://user-images.githubusercontent.com/93257509/165770509-281efdfc-bcf1-4439-997b-bd58ecf157f0.png)


It doesn't occur in SBS mode.
![image](https://user-images.githubusercontent.com/93257509/165770322-19adf61e-e8f0-494f-a682-4369d4aa4ba6.png)

**Comment by rr-** [comment]
@Klona13 fixed
