### ISSUE TITLE
Support new Markdown tags

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#261]
```
[p]Blue for Pickups[/p]
[s]Gold for Secrets[/s]
[t]Orange for Traps[/t]
[e]Red for Enemies[/e]
[o]Green for Objects of Interest or Interactibles[/o]
```

Remember about testing it for all themes

**Comment by Klona13** [comment]
Will it be like this?
![image](https://user-images.githubusercontent.com/93257509/164951023-668b6d84-8d84-4fed-92e6-c0cd70f0a634.png)

**Comment by rr-** [comment]
TBH I'd prefer it much more if we made these into consistent icon buttons rather than this popup. OK for the buttons to be colored.
