### ISSUE TITLE
Featured Level - New Release

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#267]
Maybe have a new level displayed on the main page like trle.net does?

![image](https://user-images.githubusercontent.com/80340234/165807026-3a699953-8c51-45e3-9bf1-08b0954ed132.png)

**Comment by Klona13** [comment]
In the new release section, the newest release will be shown.

Every time a new level is released, they go on a list. They stay on that list for a week.

While they are on that list, every time you access the website it will show one of these levels in the "New Release" feature.

If there are no levels on that list, then it will just show the last released level.

![image](https://user-images.githubusercontent.com/93257509/176098152-cc80f403-8bb8-4e85-97f8-0be709cef989.png)

**Comment by Klona13** [comment]
I'll keep an eye on this in prod for a while.
