### ISSUE TITLE
Best in <Genres> rule re-evaluation

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#276]
Fixing inconsistencies in #18 as it's not working as I originally intended. In production, the current level has no genre, yet it is "best in casual" despite other levels having the casual genre.

The original rules, every 2 weeks it updates with:
1- The level reviews must be Overwhelmingly Positive or Masterpiece
2- Is in the highest 50% of the download count
3- Cannot pick the same level twice every 3 years
4- Cycles through every genres in order before starting again

They do not work pretty well since we didn't import the download counts from trle.net. So that part of the rule should be deleted.
So delete rule 2:
~~2- Is in the highest 50% of the download count~~

and we can put two new rules instead:
- The level HAS to include this turn's Genre.
- If no level in that genre applies to the current rules, the genre is skipped.

**Comment by rr-** [comment]
@Klona13 we'll fill download counts eventually within a few months
the two new rules are already implemented, if there's no eligible level in action it picks a level from the whatever genre is after action.

**Comment by Klona13** [comment]
This category was created in mind for established levels, and I designed it with trle.net counts in mind. Because we decided to not add them, it makes this rule pointness.
Also this is not working as intended, if you see the category, the genre doesn't match up:
![image](https://user-images.githubusercontent.com/93257509/170884557-02be42c5-6293-4a4b-bd88-e2af3fb588f3.png)
![image](https://user-images.githubusercontent.com/93257509/170884577-c6ffbd02-aae6-4eb4-9539-469739437f7f.png)

**Comment by Klona13** [comment]
The best way to test this is with a large sample in production.
Promoting ticket.
