### ISSUE TITLE
Theme - Mystic Forest

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#279]
--primary-color: #19152e;
    --secondary-color: #31c11b;
    --bg-color: var(--primary-color);
    --fg-color: #f0edff;
    --failure-fg-color: tomato;
    --warning-fg-color: #yellow;
    --success-fg-color: #limegreen;
    --link-color: var(--secondary-color);
    --link-hover-color: #95ff85;
    --link-text-decoration: none;
    --outline-color: var(--link-color);
    --input-bg-color: #c3e4b5;
    --input-fg-color: #000;
    --button-bg-color: #45a11e;
    --button-fg-color: #fff;
    --button-hovered-bg-color: #5bbb32;
    --button-text-decoration: none;
    --label-bg-color: var(--navbar-bg-color);
    --navbar-bg-color: #0a051b;
    --navbar-active-tab-bg-color: #2f5e1c;
    --navbar-active-tab-fg-color: #c3e4b5;
    --sidebar-bg-color: var(--navbar-bg-color);
    --sidebar-padding: 1;
    --reviews-positive-bg-color: #213913;
    --reviews-neutral-bg-color: #3c3c17;
    --reviews-negative-bg-color: #4d1f1f;
    --stats-positive-bar-color: #538f38;
    --stats-neutral-bar-color: #7b6032;
    --stats-negative-bar-color: #a62626;
    --stats-hover-filter: brightness(190%);
    --message-bg-color: var(--sidebar-bg-color);
    --blockquote-bg-color: var(--bg-color);
    --blockquote-border-color: var(--link-color);

**Comment by rr-** [comment]
That's because the colors I copy-pasted from the instructions were invalid.
```diff
---warning-fg-color: #yellow;
---success-fg-color: #limegreen;
+--warning-fg-color: yellow;
+--success-fg-color: limegreen;
```
