### ISSUE TITLE
Walkthrough: 403 error

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#284]
if I am not logged in and try to write a walkthrough I receive a 403 error

![image](https://user-images.githubusercontent.com/80340234/170518494-414c1641-1205-4bc3-a315-6669183520f7.png)

**Comment by rr-** [comment]
Why should you be able to write a walkthrough as an anonymous user?

**Comment by Kubsy** [comment]
I know lol but there should be a message for the user to say that "you should login to write a walkthrough"

**Comment by rr-** [comment]
It should not be possible for them to reach this page in the first place.
We do not offer specialized pages for every possible action the user can take.

**Comment by Klona13** [comment]
The same thing happens everywhere else login is required. The error says exactly what it should.
Closing.
