### ISSUE TITLE
Profile: side scrolling bar not showing

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#285]
Sometimes when I click on my profile, the side bar is not shown and I cannot scroll down. I have to refresh to make it appear, sometimes I have to refresh twice. This issues also happens on the walkthru page but it always happens

![image](https://user-images.githubusercontent.com/80340234/170522558-311886c8-ed1e-4307-b22b-7ceed6799676.png)

**Comment by rr-** [comment]
@Kubsy do you have any errors in the console when this happens?

**Comment by Kubsy** [comment]
> @Kubsy do you have any errors in the console when this happens?

![image](https://user-images.githubusercontent.com/80340234/170542310-b66dba87-fdca-4e34-b737-0d2ab3ec8057.png)

this also happened when I checked my approved text walkthrough

**Comment by rr-** [comment]
I can't reproduce this but let's hope it will get fixed with #282
