### ISSUE TITLE
Playlist link in video walkthrough

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#289]
Posting the playlist link embeds the playlist.
It doesn't have to embed the video itself, but if the user can see all the videos listed, it would be great.

**Comment by rr-** [comment]
Embedding playlist links is technically not possible, it just embeds a video and the user needs to watch it on youtube.

**Comment by Klona13** [comment]
Ok, so the next option is to change this:
Watch the full video at -link-

to

Click here to see the full video/playlist.
