### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#295]
In the profile Library section there will be a counter for Playlist. Clicking on it, people can see the playlist but cannot add levels or see the buttons except for the owner of the playlist.

The design is similar to the walkthrough list (with the profile sidebar).

The owner of the playlist sees a search bar that can find levels quickly and add them to the list. (similar to how we search for tags)

By pressing add/enter, it is added to the list.

Columns are
Status - Level name - Review - Actions (only the owner sees this column)

There is a dropdown list with
- Unplayed (selected by default)
- Playing
- Finished
- On hold
- Dropped
- Remove

Status will update once selecting an action:
- Unplayed (no color)
- Playing (Yellow)
- On hold (Yellow)
- Finished (Green)
- Dropped (Red)
- Remove

In the review column it either says "Read" in the link text style that takes you to the review OR says "None" if there is no review.

**Comment by rr-** [comment]
Can we also add a column that links to the player's review if it's available?

**Comment by Klona13** [comment]
Added in the OP.

"In the review column it either says "Read" in the link text style that takes you to the review OR says "None" if there is no review."

**Comment by rr-** [comment]
@Klona13 Are we OK with color-coding the statuses? We'd have to coordinate the exact color values across all themes, plus there's the concern of colorblind people.

**Comment by Klona13** [comment]
@rr- We already use these colors for ratings, so we can use the same colors values for it without creating anything extra.
![image](https://github.com/rr-/TRCustoms/assets/93257509/cc14f328-5869-4f14-bfcd-96839078d2fa)
It shouldn't affect colorblind people as it's just there for style.

**Comment by rr-** [comment]
@Klona13 do you think it'd make sense to let people add "start date" and "finish date"? to let them have an idea what they were playing 5 years ago

**Comment by rr-** [comment]
Also perhaps we could also have an "on hold" status as well

**Comment by Klona13** [comment]
@rr- 

> @Klona13 do you think it'd make sense to let people add "start date" and "finish date"? to let them have an idea what they were playing 5 years ago, and also, to let people sort by most recently played (eg have most recently added levels at the top/bottom of the table)

We could add a "last updated" column that updates a date when the level is added to the list OR actions changed to the record. Otherwise I feel like there would be too much going on in the table.

> Also perhaps we could also have an "on hold" status as well

yesss

**Comment by rr-** [comment]
I took a few shortcuts when it comes to the widgets due to the technical infeasibility of the original designs – namely, I went with modals instead of responsive widgets. I also added a button on the level sidebar "add to my playlist" on top of the auto-complete thing you asked.

**Comment by Klona13** [comment]
When i click this it doesn't refresh the page. It works fine when using it from a level page, but if you are already in the playlist page, nothing happens.
![Screenshot_20230807_150156_Chrome](https://github.com/rr-/TRCustoms/assets/93257509/d1bdd27c-cacc-43ea-a859-735c012074ad)

**Comment by Klona13** [comment]
Can it be ordered like this by default?
![image](https://github.com/rr-/TRCustoms/assets/93257509/de8163c8-5afe-44c5-85bb-cde0fda7147f)

**Comment by rr-** [comment]
Updated

**Comment by rr-** [comment]
Done, but I also extended this rule to the `status` column for the sake of improving padding between columns on desktop
