### ISSUE TITLE
Tag seperation

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#296]
Separate tags. Give each level 2 tags and then delete the main tag. (Let me know to check before deleting)

| Main tag      | New tag 1 | New tag 2 |
|---------------|-----------|-----------|
| Rome/Greece   | Rome      | Greece    |
| Nordic/Celtic | Nordic    | Celtic    |
| Cave/Cat      | Caves     | Catacombs |
| Base/Lab      | Base      | Lab       |
| Alien/Space   | Alien     | Space     |

**Comment by rr-** [comment]
Available on production, old tags still in use and OK to be deleted
