### ISSUE TITLE
Theme - Campfire Gathering

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#299]
--primary-color: hsl(15deg 50% 9%);
    --secondary-color: #e61c02;
    --bg-color: var(--primary-color);
    --fg-color: #ffdeb2;
    --failure-fg-color: tomato;
    --warning-fg-color: yellow;
    --success-fg-color: limegreen;
    --link-color: var(--secondary-color);
    --link-highlight-bg-color: #601c1c;
    --link-highlight-fg-color: #edd0d0;
    --link-text-decoration: none;
    --outline-color: var(--link-color);
    --input-bg-color: #e0a8a8;
    --input-fg-color: black;
    --button-bg-color: #a11e1e;
    --button-fg-color: white;
    --button-hovered-bg-color: #c44040;
    --button-text-decoration: none;
    --label-bg-color: var(--navbar-bg-color);
    --navbar-bg-color: #160a0b;
    --navbar-active-tab-bg-color: #601c1c;
    --navbar-active-tab-fg-color: #edd0d0;
    --sidebar-bg-color: var(--navbar-bg-color);
    --sidebar-padding: 1;
    --reviews-positive-bg-color: #213913;
    --reviews-neutral-bg-color: #3c3c17;
    --reviews-negative-bg-color: #4d1f1f;
    --stats-positive-bar-color: #538f38;
    --stats-neutral-bar-color: #7b6032;
    --stats-negative-bar-color: #a62626;
    --stats-hover-filter: brightness(190%);
    --walkthroughs-hover-filter: brightness(140%);
    --message-bg-color: var(--sidebar-bg-color);
    --blockquote-bg-color: var(--bg-color);
    --blockquote-border-color: var(--link-color);
}

![image](https://user-images.githubusercontent.com/93257509/171968780-bc5093da-b50e-41ce-86b0-bb23929d54d3.png)

**Comment by Klona13** [comment]
i really hate it

**Comment by rr-** [comment]
Why should we add it then?
Is there anyone who says yay for this?

**Comment by Klona13** [comment]
i havent showed it yet. I made it and thought it was cute, then made a ticket and now I hate it.

I'll give it to delca for touch ups.

**Comment by Klona13** [comment]
closing this trash
