### ISSUE TITLE
Levels: pending approval can be seen to all users by changing numbers on search bar

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#301]
Some people were able to see the pending approved levels, not too sure how but presumably **changing the number 3420 to 3421**. This came up with Mahetus' full version of forbidden Place. Same for Ilaria's new level

https://trcustoms.org/levels/3421
![image](https://user-images.githubusercontent.com/80340234/174041568-30acbc0a-4466-4ec5-81ed-4cc14af60309.png)

**change 3421 to 3422 in the search bar**
![image](https://user-images.githubusercontent.com/80340234/174041750-4792de57-812d-4bb0-ae92-844d2ed87855.png)

**Comment by Klona13** [comment]
Normal behavior.
