### ISSUE TITLE
Best in <Genre> not updating

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#304]
Best in <Genre> featured levels section is not updating.
It's supposed to update every 2 weeks, but it has been more than that.
Still no update.

**Comment by rr-** [comment]
Are you sure?

| Date | Name | Type | Genre |
| --- | --- | --- | --- |
| May 29, 2022, 5 a.m.      | HyperSquare (id=2681)                          | Best in genre | Fantasy (id=10)
| May 15, 2022, 5 a.m.      | LB Advent Calendar 2007 - Snowwhite (id=1713)  | Best in genre | Exploration (id=22)
| April 30, 2022, 5 a.m.    | The Skribblerz Stonez (id=1577)                | Best in genre | Casual (id=7)
| April 15, 2022, 5 a.m.    | The Rescue 11 - The Hidden Experiment (id=698) | Best in genre | Adventure (id=2)
| March 31, 2022, 1:22 p.m. | Jade Empire (id=1557)                          | Best in genre | Action (id=1)

**Comment by rr-** [comment]
Nvm I missed June

**Comment by Klona13** [comment]
Yes, it hasn't updated for more than a month. It should update every 2 weeks.
![image](https://user-images.githubusercontent.com/93257509/177045925-c8cd2f2f-4fd0-4e91-95de-ce9649e739ec.png)

**Comment by rr-** [comment]
There was an issue on production which I had fixed on develop.
Featured a level manually for now.

The feature will continue to be broken on production until we deploy the current increment with the bugfix.

**Comment by Klona13** [comment]
I'll keep an eye on this in prod after the fix is deployed
