### ISSUE TITLE
X button for added entities is not visible

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#305]
It seems that the issue is that they are the same color. This affects all of the 3 new themes.
What do you suggest we do?

Not highlighted:
![image](https://user-images.githubusercontent.com/93257509/176743089-a0263700-7575-42ae-a91d-0a16aacd9aae.png)

Highlighted by cursor:
![image](https://user-images.githubusercontent.com/93257509/176743095-fd7fb5f9-3396-4c29-a9a2-ce9bd9a64ca4.png)

**Comment by rr-** [comment]
I'll make it the same as the text color.
