### ISSUE TITLE
Inflated review count on the level list

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#309]
According to Kubsy, this bug affects levels with Multiple Authors.

As you see, the review count on the level list is inflated for certain levels.
![image](https://user-images.githubusercontent.com/93257509/177791085-dba4f690-4a2a-43b9-ab97-d90d81712e67.png)

 These levels actually have 24 and 13 reviews respectively.

**The bug does not affect the count in the level page, it's only on the level list.**

**Comment by rr-** [comment]
I denormalized the field which means it's no longer computed with complex SQL queries and instead becomes physical, getting updated whenever someone reviews or deletes a review.

**Comment by Klona13** [comment]
The page I used to test now always crashes:
https://staging.trcustoms.org/levels/1
