### ISSUE TITLE
Level pages crashing on staging

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#311]
It just loads nothing. Blank page.
Example of affected pages:
https://staging.trcustoms.org/levels/2
https://staging.trcustoms.org/levels/7
https://staging.trcustoms.org/levels/9
https://staging.trcustoms.org/levels/10

Console error shows this...
![image](https://user-images.githubusercontent.com/93257509/178004636-12b8327d-fd59-44e9-af02-fa8975b52530.png)

Example pages that are NOT affected by the crash:
https://staging.trcustoms.org/levels/4
https://staging.trcustoms.org/levels/6

**Comment by rr-** [comment]
Fixed
