### ISSUE TITLE
Level list filter - Tag order

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#320]
Instead of ordering them alphabetically, order by last updated.

**Comment by rr-** [comment]
Last updated… or usage (# of levels they appear in)?

**Comment by Klona13** [comment]
Usage (i think it's the same field)

**Comment by Klona13** [comment]
This is just for the filter area not the Tab, but if it's troublesome to change one of them then we could just do both. Plus seeing the latest updated tag is better then seeing them alphabetically in any case.

For the filter area, this is so that users don't always see the same tags, and it will encourage them to click on ones they haven't seen before. Kind of makes the site look extra dynamic too 😌

**Comment by Klona13** [comment]
It's still like that currently, but with this change it's gonna be more varied and not limited to what just happens to come first.
![image](https://user-images.githubusercontent.com/93257509/210132683-0cdc03d5-7bc4-4a2a-a7e2-338659fc1ac4.png)
