### ISSUE TITLE
Not tabbing (or spacing) review makes it elongated affecting the whole webpage

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#321]
I am not sure if it's intended or not but if the user didn't make sure to tab the sentences in their reviews, then the whole webpage shifts to the right and affects images too 

note: I zoomed out to see the whole webpage 

it seems to happen when a user does this:
```
hi
```

![image](https://user-images.githubusercontent.com/80340234/182832931-a2f2667e-85ad-4aae-8fbb-f1ac99daedc9.png)

**Comment by rr-** [comment]
This requires `<pre>`, or in other words, this syntax:

<pre>
```
asdasda
```
</pre>
