### ISSUE TITLE
Best in Genre hasn't updated

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#324]
![image](https://user-images.githubusercontent.com/93257509/190431696-f7a6ff44-dcb1-4133-96f4-777d2bfc5769.png)

It is supposed to skip a Genre when the conditions for it are not met.

According to the DB, it hasn't refreshed since 3rd August. It seems that the condition set prevents it from ever checking again when it fails a check. In that case, it needs to skip to the one after it. Even if it fails 10 in a row, it should jump to the 11th (and if that also fails, then 12th).

IF by any means it does one full cycle through the genres and finds nothing, then it holds the check for 2 weeks (when it's usually updated).

**Comment by rr-** [comment]
Fixed in develop.
Triggered the fix manually on production.
