### ISSUE TITLE
Long phrases with no spaces causing page to mess up

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#327]
Possible places:
- Home page: Featured level name
- Level page: level title
- Level list: level title

![image](https://user-images.githubusercontent.com/93257509/193158006-de40ae30-d147-4c2f-bc09-aeb46933a84e.png)

![image](https://user-images.githubusercontent.com/93257509/193157994-31e9736a-014b-48a3-a11f-fabfe0859428.png)

**Comment by Klona13** [comment]
There is an inconsistency here:
![image](https://user-images.githubusercontent.com/93257509/193313213-38a8fab4-facf-441a-afb9-bde33a0d9f5c.png)

**Comment by rr-** [comment]
I can't do anything about it, sorry. Not without some code gymnastics anyway.
