### ISSUE TITLE
Duplicate Tag Merging

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#337]
There were 2 exactly same tags for some reason "TR2 Gold".

So I tried to merge them and it just exploded... as in it just deleted itself and from the two levels that used it.

I tested this on staging. Adding a double space allows the creation of the same tag AGAIN.
![image](https://user-images.githubusercontent.com/93257509/207090357-7616f593-376b-410d-a8bc-019db7826a78.png)
![image](https://user-images.githubusercontent.com/93257509/207090435-67e33a15-4790-45ea-9aaf-4294e2e748a7.png)

And a third time if i add a third space:
![image](https://user-images.githubusercontent.com/93257509/207090548-1f7ab628-1d68-461d-a506-2a8d7e65e86f.png)

This ONLY occurs if the tag has space BETWEEN things. So it won't occur if the space is at the start or end of the string.

**Comment by rr-** [comment]
So I tried to merge them and it just exploded... as in it just deleted itself and from the two levels that used it.



So long as both levels  have the TARGET tag it is the expected behavior.
