### ISSUE TITLE
Level list filter - flexible search bar

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#338]
The search bar is universal. It searches through level title, authors, tags, and genres.

**Comment by rr-** [comment]
I added a prefix-based search for genres and tags (`explor` will find levels with the genre `exploration`), and exact match search for engines (`tr1` will find levels made on TR1 engine).
Author names and level names search anywhere so `ful` will find levels by DJ Full and `mona` will find `movement at the monastery`.

**Comment by Klona13** [comment]
That sounds great!

**Comment by Klona13** [comment]
Ok, in this case you can just change this to "Global Search:"
![image](https://user-images.githubusercontent.com/93257509/210156419-ab027fc7-ee03-4f13-800e-19090209b7c3.png)
