### ISSUE TITLE
Choosing 2004 in the year filter will skip the 2004 levels by a year

### ISSUE THREAD

**Issue by Kubsy** [rr-/TRCustoms#340]
if you choose 2004 as the year for the level filter, it will skip 2004 and go straight to 2005 which makes the year filters from 2004-2010 messed up
![Bez tytułu](https://user-images.githubusercontent.com/80340234/211061668-dbf2e00b-fe8d-45d6-9c02-a6f051dda288.png)

**Comment by rr-** [comment]
Fixed. The bug was that the max date filter was inclusive, and these levels had their publication date set to _exactly_ at midnight.
