### ISSUE TITLE
Awards - Standard artefacts

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#342]
Dual Pistols
"You released 10 levels that are up to standard."
Condition: User has released 10 or more levels with at least mixed rating. (Approved levels)

Iris
"You have submitted 25 video walkthroughs."
Condition: Approved walkthrough (type: video)

Bestiary
"You have submitted 25 text walkthroughs."
Condition: Approved walkthrough (type: text)

Seraph
"You've joined the site in its first year."
Condition: Account is active and join date is between (and equal to) 1 Apr 2022 to 1 Apr 2023.

Werner's Broken Glasses
"You are one of the first 20 reviewers for 500 levels."
Condition: You have 500 reviews with review ID of 20 or less

Philosopher's Stone
"You released two levels within the same year that got an overwhelmingly positive rating."
Condition: The levels released are less than 365 days apart and achieved overwhelmingly positive (at any time)

Bone Dust
"You have updated all your levels imported from TRLE.net."
Condition: Since level edit form can't be submitted without putting genres... Check if all levels that were released by the user BEFORE 2 Apr 2022 have any genre.

The Sanglyph
"You built levels, reviewed levels, and guided others through levels. Respect!"
Condition: Built 3 levels, reviewed 30 levels, and released 10 walkthroughs. With the levels and walkthroughs being approved of course.

**Comment by rr-** [comment]
>Dual Pistols
Werner's Broken Glasses
"You are one of the first 20 reviewers for 1000 levels."

Can we make it less? This number seems insanely high.
Especially combined with my opinion that reviews are a damn chore and we should let people just play the level, add to their list and rate it, any text being optional…

>Philosopher's Stone
>You have held the position of the highest rated level for more than 1 year

If this is about checking if any of the author's levels had retained the "masterpiece" status at any point for more than 1 year, the computational cost of calculating this is obscenely high.

>Bone Dust
>You have updated all your previous levels
>Condition: User has updated all of their levels that were released before 2 Apr 2022.

We don't track who does the update at what time, only when the level was updated, so all I can do is "all of your levels that were released before 2 Apr 2022 were updated by you or someone else". (This will essentially apply to everything when you'll go on an edit spree to upload higher res screenshots to everything)

>The Sanglyph
>You built 3 levels with mixed rating, reviewed 30 levels, and released 10 walkthroughs.

So the user has to have levels with 3 mixed rating at the time of checking for this achievement? (Doable but makes little sense to me)
Or do they need to have 3 unique levels that in their past have had mixed rating at some point? (Computationally infeasible)

**Comment by Klona13** [comment]
Updated with new info! @rr-

**Comment by Klona13** [comment]
![image](https://user-images.githubusercontent.com/93257509/225337290-e2d4c53d-c828-446b-a5bb-f85e5d56f83e.png)
- has 26 text walkthroughs but the Bestiary is missing
- joined on 1 April but Seraph is missing

![image](https://user-images.githubusercontent.com/93257509/225338333-8288274a-e770-4fe0-89c3-af04d2c14faf.png)
- Bone dust should be there cause the user's level(s) has genres and it was released before 2nd April.
