### ISSUE TITLE
Filter order swap

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#345]
Swappity Swappitus:
- TEN should be under TR5
- Invert the ratings order
![image](https://user-images.githubusercontent.com/93257509/218489899-4eda6950-170d-49cf-9f76-b3cc0aa0cc28.png)

**Comment by Klona13** [comment]
Invert the ratings too so that masterpiece is first and failure is last please. @rr-

**Comment by rr-** [comment]
Fixed, the fix is now getting deployed.
