### ISSUE TITLE
Awards - Standard artefacts (second batch)

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#347]
Gate Key
"50 users have added one of your levels to their playlist"
Condition: User gets the award if one of their levels is added to a playlist 50 times.

Smuggler's Key
"You reviewed 5 levels on the same or next day of release."

Werner's Notebook
"You reviewed 5 levels belonging to one author."

Nightmare Stone
"3 of your levels have at least 1 tag."

Magic Stones
"You topped up 3 of your levels with tags!"
Condition: User has 3 levels, and each level has 10 tags.

Wraith Stone
"You completed 20 levels in your playlist."
Condition: Playlist contains 20 levels marked "Finished".

Excalibur
"You completed 100 levels in your playlist."
Condition: Playlist contains 100 levels marked "Finished".

Mjölnir
"You completed 250 levels in your playlist."
Condition: Playlist contains 250 levels marked "Finished".

Demon's Heart
"You finished 50 levels with a negative rating."
Condition: 50 levels are in the playlist that have any of the negative ratings.

Spear of Destiny
"You finished 50 levels with a positive rating."
Condition: 50 levels are in the playlist that have any of the positive ratings.

Chirugai
"You have returned after years of inactivity."
Condition: You've released a level in the past, and then released another level after 10 years apart.

First Obscura Painting
"You reviewed 20 levels with a review amount between 1 and 5!"
Condition: 20 reviews between 1 and 5.

Second Obscura Painting
"You reviewed 20 levels with a review amount between 6 and 10!"
Condition: 20 reviews between 6 and 10.

Third Obscura Painting
"You reviewed 20 levels with a review amount between 11 and 15!"
Condition: 20 reviews between 11 and 15.

Fourth Obscura Painting
"You reviewed 20 levels with a review amount between 16 and 20!"
Condition: 20 reviews between 16 and 20.

Fifth Obscura Painting
"You reviewed 20 levels with a review amount between 21 and 25!"
Condition: 20 reviews between 21 and 25.

**Comment by Klona13** [comment]
![chirugai](https://github.com/rr-/TRCustoms/assets/93257509/7b6c7b2e-7253-4a4e-a954-b1794ff98400)
![gate key](https://github.com/rr-/TRCustoms/assets/93257509/fe7db298-8bc3-4333-9e22-0347b00e4be8)
![magic stones](https://github.com/rr-/TRCustoms/assets/93257509/9cdd6171-0537-441b-b9af-6d805aa54ef9)
![nightmare stone](https://github.com/rr-/TRCustoms/assets/93257509/9d959490-858b-4dc5-873a-2baad80c65a1)
![obscura1](https://github.com/rr-/TRCustoms/assets/93257509/eb24b5c1-1659-486d-b570-0f3085922671)
![obscura2](https://github.com/rr-/TRCustoms/assets/93257509/7bb14e11-c018-4b1f-8f24-85292aac9519)
![obscura3](https://github.com/rr-/TRCustoms/assets/93257509/7aba9969-a05c-4f1c-b980-6c06f8bd7f42)
![obscura4](https://github.com/rr-/TRCustoms/assets/93257509/d13bacf9-e0f3-4522-8f4a-bc73ef7ed813)
![obscura5](https://github.com/rr-/TRCustoms/assets/93257509/aa530d8f-501e-4f7f-842f-e233815d4ff5)
![smugglers key](https://github.com/rr-/TRCustoms/assets/93257509/75052bad-50a0-4756-85ad-6cf4bff33d5a)
![spear of destiny](https://github.com/rr-/TRCustoms/assets/93257509/7e83d620-944f-4a93-ab4a-ce6c6a3bd5ce)
![tome of ezekiel](https://github.com/rr-/TRCustoms/assets/93257509/67a609ee-47e3-4746-a05d-fb157e310a4a)
![werners notebook](https://github.com/rr-/TRCustoms/assets/93257509/2831e874-694a-43fe-b33c-08997e9c4345)

**Comment by Klona13** [comment]
Can it be updated for existing users? @rr-

**Comment by rr-** [comment]
Done @Klona13

**Comment by Klona13** [comment]
The Chirugai isn't appearing properly.
![image](https://github.com/rr-/TRCustoms/assets/93257509/d7e27acb-db83-4da3-95df-80367384d6a0)

**Comment by rr-** [comment]
@Klona13 fixed

**Comment by Klona13** [comment]
I didn't reach 20 reviews and it gave the award.
![image](https://github.com/rr-/TRCustoms/assets/93257509/65c64a80-441d-49b4-9862-6597575e3983)

**Comment by rr-** [comment]
@Klona13 you did:

1. https://staging.trcustoms.org/levels/50/: reviewed as #1
2. https://staging.trcustoms.org/levels/51/: reviewed as #1
3. https://staging.trcustoms.org/levels/52/: reviewed as #2
4. https://staging.trcustoms.org/levels/53/: reviewed as #2
5. https://staging.trcustoms.org/levels/54/: reviewed as #2
6. https://staging.trcustoms.org/levels/55/: reviewed as #2
7. https://staging.trcustoms.org/levels/56/: reviewed as #2
8. https://staging.trcustoms.org/levels/57/: reviewed as #2
9. https://staging.trcustoms.org/levels/58/: reviewed as #2
10. https://staging.trcustoms.org/levels/61/: reviewed as #2
11. https://staging.trcustoms.org/levels/62/: reviewed as #2
12. https://staging.trcustoms.org/levels/68/: reviewed as #2
13. https://staging.trcustoms.org/levels/70/: reviewed as #2
14. https://staging.trcustoms.org/levels/75/: reviewed as #2
15. https://staging.trcustoms.org/levels/76/: reviewed as #2
16. https://staging.trcustoms.org/levels/77/: reviewed as #2
17. https://staging.trcustoms.org/levels/72/: reviewed as #1
18. https://staging.trcustoms.org/levels/73/: reviewed as #1
19. https://staging.trcustoms.org/levels/74/: reviewed as #1
20. https://staging.trcustoms.org/levels/24/: reviewed as #2
21. https://staging.trcustoms.org/levels/80/: reviewed as #2

**Comment by Klona13** [comment]
that's strange cause the counter shows 19, at least it worked.

**Comment by Klona13** [comment]
It should say 3 instead of min levels in the description @rr- 
![image](https://github.com/rr-/TRCustoms/assets/93257509/0d28e57e-c859-4382-a1a2-f0e3586cb912)

**Comment by rr-** [comment]
@Klona13 fixed

**Comment by Klona13** [comment]
@rr- 
There is an issue here _i think_, or maybe i got it wrong
https://github.com/rr-/TRCustoms/blob/develop/backend/trcustoms/awards/specs/smugglers_key.py

min_levels should be 5 cause
```Smuggler's Key
"You reviewed 5 levels on the same or next day of release."```

**Comment by rr-** [comment]
@Klona13 requirement lowered (sorry for this typo) and the description updated.

**Comment by Klona13** [comment]
# Description for the guide
Gate Key
50 users must add your level to their playlist.

Smuggler's Key
Review a level 24 hours from release.

Werner's Notebook
Review 5 levels belonging to one author.

Nightmare Stone
3 of your levels should have at least 1 tag.

Magic Stones
Top up 3 of your levels with tags.

Wraith Stone
Mark 20 levels in your playlist as Finished.

Excalibur
Mark 100 levels in your playlist as Finished.

Mjölnir
Mark 250 levels in your playlist as Finished.

Demon's Heart
Mark 50 negatively reviewed levels in your playlist as Finished.

Spear of Destiny
Mark 50 positively reviewed levels in your playlist as Finished.

Chirugai
Released a level, and then release another level after 10 years.

First Obscura Painting
Review 20 levels that have a review amount between 1 and 5.

Second Obscura Painting
Review 20 levels that have a review amount between 6 and 10.

Third Obscura Painting
Review 20 levels that have a review amount between 11 and 15.

Fourth Obscura Painting
Review 20 levels that have a review amount between 16 and 20.

Fifth Obscura Painting
Review 20 levels that have a review amount between 21 and 25.
