### ISSUE TITLE
Reviewer sidebar redesign

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#352]
Similar to the sidebar in the homepage. They should also behave the same when you hover them (same opacity settings).
![image](https://user-images.githubusercontent.com/93257509/229352082-823dfba3-1af2-43b1-9fa5-a71b30ffd304.png)

Note that the sidebar should be present in all review tab pages.

**Comment by Klona13** [comment]
I noticed it changes the brightness and not opacity. This change was also reflected on the homepage when it shouldn't.

**Comment by rr-** [comment]
Opacity manipulation caused the images to look dull and kind of broken. LMK how we can go about this

**Comment by rr-** [comment]
In both cases? Or just homepage?
