### ISSUE TITLE
OpenGraph social media previews

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#357]
OpenGraph social media previews

**Comment by rr-** [comment]
I only added a special rule for the level page.
LMK if we should provide a description and/or image to any more pages.

**Comment by Klona13** [comment]
Everything is in working order. Few changes need to be done:
- [/levels](https://trcustoms.org/levels) has the wrong description
- Change the logo image to:

![logopng](https://user-images.githubusercontent.com/93257509/233429658-eec5ff28-0007-400f-b489-b7373c407424.png)

**Comment by Klona13** [comment]
https://trcustoms.org/reviews/authors
Reviewer catalogue pic
Search for custom level critics.

https://trcustoms.org/reviews/level_suggestions
Less known levels pic
Find levels that don't have a lot of reviews, there might be a hidden gem somewhere.
