### ISSUE TITLE
Headers for reviewer lounge

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#360]
Put headers for pages of the reviewer lounge.
For less known levels page, add a note too:
![image](https://user-images.githubusercontent.com/93257509/234227366-9e838174-41c5-4151-ab04-60d4044ba38e.png)

**Comment by rr-** [comment]
I don't understand.

**Comment by Klona13** [comment]
like
![image](https://user-images.githubusercontent.com/93257509/234371934-81a71a9f-47b6-496f-8d88-7e9062b2766e.png)

**Comment by Klona13** [comment]
It should say Less known levels:

![Image](https://github.com/rr-/TRCustoms/assets/93257509/02de6b1f-f3cc-45d5-a85d-a73f82ea4e95)
