### ISSUE TITLE
Ask to add the reviewed level to the playlist

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#368]
Reviewed levels are automatically added to playlist as Finished.
If a level is already there in the playlist, it's not added.

**Comment by Kubsy** [comment]
maybe to expand on that, when the user downloads the level, the level would add to playlist as "playing" etc

**Comment by rr-** [comment]
@Klona13 wdyt?

**Comment by rr-** [comment]
Actually this will be a modal whether to mark (= add or update) the reviewed level as finished.

**Comment by Klona13** [comment]
It works when updating a review, but it doesn't show up when creating a new review. @rr-

**Comment by rr-** [comment]
@Klona13 Fixed
