### ISSUE TITLE
Scion award change

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#377]
Before:
50 100 250 500 1000
After:
10 50 100 250 500

**Comment by Klona13** [comment]
@rr- 
After the update goes live, would it be possible to recalculate it for everyone?
During testing, I already had 50 walkthroughs but still had the Bronze (which is for 10 walkthroughs). I simply went to one of the walkthroughs and "updated" it, and it refreshed to the Silver tier (for 50 walkthroughs) correctly.

**Comment by rr-** [comment]
Yes, naturally.

**Comment by Klona13** [comment]
@rr- i forgot to mention this should also reflect on the item collection guide as it still shows the old numbers
![image](https://github.com/user-attachments/assets/293df6fd-0cbb-4e95-a98e-4f66e1b798ef)

**Comment by rr-** [comment]
Fixed
