### ISSUE TITLE
Released level awards persistence 

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#382]
Dragon award stays when the condition no longer applies. It can be abused by adding other authors to a highly rated level and then removing them.

To prevent this kind of misuse, that award should downgrade or be removed as per the condition it aligns with.

**Comment by rr-** [comment]
Fixed both Bone Dust and Dragons.

**Comment by Klona13** [comment]
@rr- It seems this issue may also extends to other awards too where released levels are involved:
- Dual Pistols
- Philosopher's Stone
- The Sanglyph
- Chirugai

I checked Magic stones and nightmare stone, they are working **correctly** and getting removed when the condition no longer applies.

**Comment by rr-** [comment]
Fixed the four awards.

**Comment by Klona13** [comment]
@rr-  i just noticed this award also has the same dependency. so it should be removed if it no longer applies.
- [ ] Gate Key: 50 users must add your level to their playlist.

**Comment by rr-** [comment]
@Klona13 fixed
