### ISSUE TITLE
Reviewing page guideline box update

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#385]
It's time this line is added...
![image](https://github.com/user-attachments/assets/d40f3f44-daff-4cea-b0c0-e475dfdc7034)

NEW text:
Remember to stay respectful and constructive, and avoid excessive profanity.
The review needs to be written in English.

**Comment by rr-** [comment]
How about: The review needs to be written in English. to stay more in-line with the mood of the first sentence, where we do not use 'Please'?

**Comment by Klona13** [comment]
> How about: The review needs to be written in English. to stay more in-line with the mood of the first sentence, where we do not use 'Please'?

yes that's better!

**Comment by rr-** [comment]
Ready on staging

**Comment by Klona13** [comment]
> Ready on staging

checked. can go live!

**Comment by rr-** [comment]
Pushed to prod
