### ISSUE TITLE
Level page redesign

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#387]
Introduction of tabs and less buttons in the sidebar. Some actions will be transferred to individual tabs.
Overview will have the images and description
![image](https://github.com/user-attachments/assets/843bb8eb-cfe2-4974-9297-c668c937a23a)

For the walkthrough tab, we get rid of the modal and have everything needed in the tab itself.
![image](https://github.com/user-attachments/assets/81734863-6593-4e6c-a81d-50815999ea0a)

Other tabs will be discussed in their own ticket. #388 #389

**Comment by Klona13** [comment]
This happens with infinite scroll enabled @rr- 
![image](https://github.com/user-attachments/assets/b5549868-ffbb-4ca8-bc5c-088135579726)

**Comment by Klona13** [comment]
Text walkthrough update button asking for a URL @rr- 
![image](https://github.com/user-attachments/assets/a39d0c50-6922-45e9-a35f-c1dafa846b6a)

**Comment by Klona13** [comment]
I checked the separate walkthrough page, and this text appears twice now:
![image](https://github.com/user-attachments/assets/256ea766-db41-4847-98de-ebf1562de2e4)

**Comment by rr-** [comment]
@Klona13 fixed both issues

**Comment by Klona13** [comment]
@rr- 
- I think youtube embeds should be 16:9 rather than 4:3. Nobody really uploads walkthroughs in 4:3, which also takes up way too much space on the screen vertically with black bars.

- The date is a link that leads to the walkthrough page.
- Update date never shows up, but it shows of a really old one for some reason: https://staging.trcustoms.org/levels/11/walkthroughs
![image](https://github.com/user-attachments/assets/1000f3b6-af69-4aea-8d23-62a305f2dc25)

- Walkthrough author would only see 1 button hidden behind the burger menu, which is strange. Only the mod/super users should see the burger menu
![image](https://github.com/user-attachments/assets/f6009171-3bb5-46d9-abc4-c5a5e893be59)

**Comment by rr-** [comment]
> [@rr-](https://github.com/rr-)
> 
> * I think youtube embeds should be 16:9 rather than 4:3. Nobody really uploads walkthroughs in 4:3, which also takes up way too much space on the screen vertically with black bars.

Fixed

> * The date is a link that leads to the walkthrough page.

I noticed you found a way to access our dedicated video walkthrough pages even though we didn't have a visible link to them. This was good feedback and inspired me to add such link, thinking users might enjoy having access to it. And since timestamps often function as permalinks to the related material, I figured I'd put it there.

> * Update date never shows up, but it shows of a really old one for some reason: https://staging.trcustoms.org/levels/11/walkthroughs

This is a bit controversial, but I changed it to only show the last update date if it's different from the publishing date. As a reminder, any action on an item, including rejecting or approving alone, will update this date.

> * Walkthrough author would only see 1 button hidden behind the burger menu, which is strange. Only the mod/super users should see the burger menu

Thanks. I've changed the burger menu to only display if it contains more than 1 button.

**Comment by Klona13** [comment]
A few more comments...

The secondary button color:
- I think the opacity should be increased from 0.3 to 0.65 to increase some attention to them. They are a little harder to see in lighter modes.
- Since sepia flashback theme is the only dark theme with black text on these buttons, it will also get 20+ more lightness on top of the point above.
- Metropolis and Robotic themes have a hue shift for the button, it makes it look purple and pink on their themes respectively.
- Also to further simplify things a bit, burger menu button should use the same color as the secondary action buttons.

Regarding walkthrough tab:
- Swap the position of posted and updated to keep the posted date in one (imaginary) column.
- Randomize the position of walkthroughs each time, but not when losing focus on the browser and returning. (only a full refresh)
- What do you think of this instead of the date hyperlink:
![image](https://github.com/user-attachments/assets/8ce47257-8881-4b99-bc5d-0b09f6971625)
- Update date should only be there to catch a user's eye to realize it's up to date. So it should not exist for a walkthrough at all, even after approval unless the content of it is updated in any way.

**Comment by rr-** [comment]
@Klona13 addressed

**Comment by Klona13** [comment]
@rr- 
- missing space before "or"
- missing updated date after changing something
![image](https://github.com/user-attachments/assets/44101ba0-5d20-4dc7-a286-fbccbe3410f2)

**Comment by rr-** [comment]
> [@rr-](https://github.com/rr-)
> 
> * missing space before "or"

Fixed

> * missing updated date after changing something
>   ![image](https://github.com/user-attachments/assets/44101ba0-5d20-4dc7-a286-fbccbe3410f2)

This requirement is in contraction with this one:

>Update date should only be there to catch a user's eye to realize it's up to date. So it should not exist for a walkthrough at all, even after approval unless the content of it is updated in any way.

**Comment by Klona13** [comment]
@rr- let me reword that part:
If updated in any way, the updated date only shows up if:
- Level has been already approved
- Date is not the same as date posted

**Comment by rr-** [comment]
@Klona13 fixed. Included the same fix for levels. Also changed the level listing rows to be more concise with dates.
