### ISSUE TITLE
Level page - Ratings tab

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#388]
As a part of the decoupling, it will require changes across the site. (Placement of the action button for users is still being discussed)

# Level page
On the level page, there will be a tab (#387) for ratings where it will show the ratings left by players. There is also a spider graph that shows data based on the ratings. (#396) 
![image](https://github.com/user-attachments/assets/ac1a57aa-ea61-44cf-a1c1-f11a47a19ce4)

**Ignore the calculate checkboxes**

**Comment by Klona13** [comment]
could you perhaps experiment with the looks for this? to replace the list in the original post as that one has no room for mod actions or edit if the user wants to change something
![image](https://github.com/user-attachments/assets/9fa711c1-427e-4e16-9bb9-02aea2580182)

**Comment by rr-** [comment]
It's currently in staging and I think it looks poorly, especially for the levels with more ratings.

**Comment by Klona13** [comment]
As discussed, we're going back to the table view for ratings (without the calculate column). Also if the updated date is the same as submission date, it can just say "Never".
For action buttons, ONLY the super user can delete. Normal mods don't have action buttons here in the ratings tab.

**Comment by rr-** [comment]
@Klona13 this is ready for testing.

**Comment by Klona13** [comment]
@rr- it doesnt allow sorting by rating (Positive, Mixed, Negative)
![image](https://github.com/user-attachments/assets/faa6d344-7685-4b6f-b51e-46730ae49a2b)

**Comment by rr-** [comment]
@Klona13 fixed

**Comment by Klona13** [comment]
@rr- Regular mods shouldn't have the burger menu to edit/delete ratings.

Normal users shouldn't be able to see it too since they have a button already to update their rating. They shouldn't be able to delete it
![image](https://github.com/user-attachments/assets/fe00a423-11e1-4496-807e-b351fa1e1f70)

**Comment by rr-** [comment]
@Klona13 removed as per our conversation
