### ISSUE TITLE
Level page - Review tab

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#389]
Due to decoupling, we get rid of the banner that shows if a review is positive/mixed/negative since they are not related to ratings anymore.
![image](https://github.com/user-attachments/assets/2f635acc-1793-4974-8174-9a201a2cba13)

**Comment by Klona13** [comment]
For reviews, updated date should not show if one of the following is true:
- Update date is March 31, 2022 or before
- Updated date = Posted date
@rr-

**Comment by rr-** [comment]
@Klona13 fixed
