### ISSUE TITLE
User profile redesign

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#390]
To accomodate the rating/review decoupling and maintain design consistency, some changes will be done in the user profile too. As a side effect, this should also make other users' playlists more accessible to people cause it will be easily seen in a tab.

The About section will always be there at the top, no changes to that.

Below, instead of showing each section separately, it will show tabs. If a tab is empty, it won't appear. So if someone has only walkthroughs, the walkthrough tab will be there. The ONLY tab that presists is the playlist tab, so if a user has nothing at all they can only see the playlist tab.

![image](https://github.com/user-attachments/assets/d5e7dc60-56f0-4e32-a7bb-127f17789620)

**Comment by Klona13** [comment]
Tab order should be like the mockup, but since the level page has ratings before reviews, we'll adapt to that:
Levels - Ratings - Reviews - Walkthroughs - Playlist

**Comment by rr-** [comment]
Thanks @Klona13 , addressed.

**Comment by Klona13** [comment]
- [ ] When switching a tab, the screen moves back to the top on its own. I think it shouldn't move at all.
Usually people want the screen to stay where it is even if they switch tabs, so it doesn't need to scroll down to the clicked tab either as they might already be looking at something on the upper part of the page.

- [ ] Updated column for Ratings doesn't put the last updated at the top when ordering. All pages where this table is present are actually affected by this.

- [ ] Playlist functionality after decoupling. It will import levels from reviews and then ratings into the playlist.
Button: Import from ratings and reviews
Message: ...  levels you rated and reviewed.

**Comment by rr-** [comment]
@Klona13 I can't reproduce the second issue. Can you show a level that exhibits the problem? The other two got fixed.

**Comment by Klona13** [comment]
- [ ] Tab switching remembers when it was lower after being repositioned up by another shorter tab. But if you manually scroll up and down slightly it's fixed. Short video: https://github.com/user-attachments/assets/883f9d49-43ee-47e5-954b-d3c0e91691ad

- [ ] Updated column dates for ratings examples:
https://staging.trcustoms.org/levels/2241/ratings
https://staging.trcustoms.org/users/876/ratings
https://staging.trcustoms.org/levels/510/ratings

- [ ] When updating one of the table lists in anyway, the page positions to the top again. It will hinder the user if they scroll down too far to edit something (with infinite scroll). https://staging.trcustoms.org/users/876/ratings

- [ ] Played levels counter on the profile don't seem to immediately update when changing something. Even after a hard refresh it seems to take some time. https://staging.trcustoms.org/users/876/ratings
^ if that's some kind of limitation, we can ignore it.

- [ ] It's not importing into playlist if there's a rating but no review. https://staging.trcustoms.org/users/876/ratings

**Comment by rr-** [comment]
> When updating one of the table lists in anyway, the page positions to the top again. It will hinder the user if they scroll down too far to edit something (with infinite scroll). https://staging.trcustoms.org/users/876/ratings

I don't see what to edit here – only level links?

**Comment by Klona13** [comment]
1. I meant to link the playlist section. Videos:
   - [When editing](https://github.com/user-attachments/assets/89bd7f14-5215-4c15-af60-623681b48be0)
   - [When removing](https://github.com/user-attachments/assets/92541117-95a5-45ff-8670-928815c6503f
)
   - [Sorting for the first time reloads everything](https://github.com/user-attachments/assets/a20cf8ed-293d-4fd9-929d-22121b220ac2)

2. That seems to work, good idea. The user wants to see who updated their review at the top and the sorting currently doesn't do that.
3. Videos:
   - [Removing Finished level requires manual refresh to update counter](https://github.com/user-attachments/assets/17b3023c-556f-42ee-ad73-15a8f6b1a4b1 
)
   - [Updating existing to Finished](https://github.com/user-attachments/assets/9c8f3815-06bc-48aa-81b4-6182dbaae415
)
   - [Importing also](https://github.com/user-attachments/assets/9a20ab64-7a21-4975-ba19-e3c5f9cdf28e
)
4. perfect. no more unexpected jumping.
5. Fixed

Different issue:
- The level tab seems to be just gone for everyone. It seems that only the author can see their own level tab now, other users can't see level tab at all even if it has levels that can already be seen on the level list.
Let's see Sabatu's profile, he has approved levels that can be seen elsewhere, but not from his profile: https://staging.trcustoms.org/users/876/

**Comment by rr-** [comment]
@Klona13 addressed the sorting issue with dates.

Regarding not updating the playlist item count – same happens with the reviews, ratings and other properties in the sidebar. Fixing this is somewhat challenging and warrants a separate ticket.

Regarding the playlist editing scroll issue - I see what you mean. This is normal behavior, where upon changing anything, we reload the entire list. I've increased the number of default playlist items to 100 as a quick fix. A proper fix is difficult to implement and would be sure to break sorting by design. Loading all records at once is also not possible – see DJ's page; it takes very long to load if I disabled paging. Actually it would make sense to offer search for such accounts in all tabs, but that should be tackled in its own ticket. LMK how you'd like us to proceed.

**Comment by Klona13** [comment]
Actually... since 1. minor issue with rare cases, I think we can leave it. The counter too, it updates but needs a refresh, not really a big deal. Functionally, everything is working. Nothing is actually broken. So this ticket is done really. @rr-
