### ISSUE TITLE
Incorrect markdown text preview box size

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#393]
When side-by-side markdown editor preview is disabled, the preview box size is not correct:
![image](https://github.com/user-attachments/assets/f9293e75-2b6f-41f6-9097-f6e832b690eb)

**Comment by Klona13** [comment]
There's some issue when scrolling down.
![Image](https://github.com/user-attachments/assets/45a032ff-6b51-4ef4-8ced-d825da04c704)
![Image](https://github.com/user-attachments/assets/4e4065b8-850e-4f2c-81f8-f8b4e2553772)

**Comment by rr-** [comment]
Fixed.
