### ISSUE TITLE
User profile - Cover images on level list are over-cropped

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#394]
The images appear narrower than 4:3 in the user profile level list.
![image](https://github.com/user-attachments/assets/26793714-b3c7-47ee-b4bc-f8bbb6216018)

I logged out of the account and looked at the same profile page where it was cropped and it doesn't seem to have that issue anymore:
![image](https://github.com/user-attachments/assets/764eb839-7840-4755-8fa6-9118964f11c4)

It's the level status causing this (Approved, Pending, Rejected). I think when the size of the bar increases vertically it crops the cover image.

**Comment by rr-** [comment]
Fixed by cropping the cover image down to 4:3, then centering the cropped image within the row.
