### ISSUE TITLE
Level page media panel consistency

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#395]
Duplicate the image with the empty area and crop + blur it in the background
![Image](https://github.com/user-attachments/assets/eb3c1121-fb43-4ea4-bb87-5f3c2961f5d0)

**Comment by Klona13** [comment]
Video play button is missing from the media panel
https://staging.trcustoms.org/levels/3110

**Comment by rr-** [comment]
@Klona13 Fixed.

**Comment by Klona13** [comment]
It seems to be affecting transparent images.

If it's impossible to disable the effect for transparent images only, it should be at least disabled for the cover image as it's not a part of the media panel.

Cover image:
![image](https://github.com/user-attachments/assets/e554eecd-3d45-4d08-9f05-364fdbb9b17f)
![image](https://github.com/user-attachments/assets/634be6ec-b6d8-4e6d-bf87-41ab204fd74a)

Media panel (extreme example):
![image](https://github.com/user-attachments/assets/9f4d2511-147b-4501-9bb6-bcc2417ab802)

**Comment by rr-** [comment]
> It seems to be affecting transparent images.
> 
> If it's impossible to disable the effect for transparent images only, it should be at least disabled for the cover image as it's not a part of the media panel.
> 
> Cover image: ![image](https://private-user-images.githubusercontent.com/93257509/389565090-e554eecd-3d45-4d08-9f05-364fdbb9b17f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDc3MjMsIm5iZiI6MTczMjU0NzQyMywicGF0aCI6Ii85MzI1NzUwOS8zODk1NjUwOTAtZTU1NGVlY2QtM2Q0NS00ZDA4LTlmMDUtMzY0ZmRiYjliMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYjNiYjk4YzdiNDFlOWQ4ZDViNzMzMjk1YjZjYzY2OGViYTY4YzJlMGJiMGJlNDdhZWZmNjAwNzhjOTg5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HKNvRCL1-Vq95F6m_A2iIlBhL-eimvmGEzkqvJ3m6TU) ![image](https://private-user-images.githubusercontent.com/93257509/389565701-634be6ec-b6d8-4e6d-bf87-41ab204fd74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDc3MjMsIm5iZiI6MTczMjU0NzQyMywicGF0aCI6Ii85MzI1NzUwOS8zODk1NjU3MDEtNjM0YmU2ZWMtYjZkOC00ZTZkLWJmODctNDFhYjIwNGZkNzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkY2UxOWZhOGFiOWU4YWZjOTg0ZWIxYjk4MTA3OGU1YjExOWY5ZGI3MWJjZmY0NmRhNDE4Mjc2ODkyY2VjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tVEqVsOtOHEC3jJTN97yLrSC0SS_Ohu2r01YT_g_EtI)
> 
> Media panel (extreme example): ![image](https://private-user-images.githubusercontent.com/93257509/389565273-9f4d2511-147b-4501-9bb6-bcc2417ab802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDc3MjMsIm5iZiI6MTczMjU0NzQyMywicGF0aCI6Ii85MzI1NzUwOS8zODk1NjUyNzMtOWY0ZDI1MTEtMTQ3Yi00NTAxLTliYjYtYmNjMjQxN2FiODAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE1MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYmFlZGY4OTcyMzMxM2Q3ZWY1ZDg2ZWMwN2NhZDBlZWI2YTA2OTc1NzMxMWVkYzc1MzM4M2IwNDM5M2EwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ns-yIBDGSKk-WUM1B4xRsuRupDVkQfMq2nOjeVDLw_I)

Not really, no. I suggest we revisit the subtle pattern suggestion from earlier.

**Comment by Klona13** [comment]
I think the blur idea is too good to pass up as it doesn't immediately bring attention to itself like patterns or solid colors.
**If the cover image on the level page doesn't inherit the blur, that would be good enough.**

Here's a realistic example of how it may cover up some inconsistent aspect ratios. Note positions 1, 3, 4, and 5.
![image](https://github.com/user-attachments/assets/73b38b7b-9d13-4ff1-b762-e4c2e4addec0)

**Comment by rr-** [comment]
@Klona13 Anyway, fixed

**Comment by Klona13** [comment]
The blur effect disappeared from the media panel too. (maybe it's a phone thing? ill check from pc in a few hours)

> Why are we allowing transparent cover images to begin with?

i suppose it's a kind of an artistic expression for the cover. it actually looks nice with that one example.
