### ISSUE TITLE
Rating tab spider graph

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#396]
Based on each rating, each score is calculated separately under 5 categories that the questionnaire is split up in.
It requires 5 or more ratings to display the spider graph, otherwise it says "More ratings are needed to display the graph."
 
**Engagement**

> 1- Do you plan on revisiting this game?
> 2- What did you think of the length of the game? 
> 7- The level lived up to the expectations set by the information on the level page. 
> 9- Ingame actions were random and lacked real sense; they felt unrelated to the story/context.

**Uniqueness**

> 4- The level featured enjoyable unique things I have never seen before.

**Quality**

> 3- The visual quality was consistently good throughout the game. 
> 5- The sound design enhanced the game's environment and set pieces. 
> 6- The builder was able to set an atmospheric tone and immerse the player. 

**Enjoyment**

> 8- How often did you get bored due to unintuitive, messy, or repetitive game design?  
> 10- What did you think of the game's difficulty? 
> 11- The level was overall fun and fulfilling in the end. 

**Stability**

> 12- There were visual glitches. 
> 13- There were audio issues. 
> 14- There were gameplay bugs.
> 15- There were bugs/problems that seriously ruined my experience.

Note:
- **Ignore the calculate checkboxes in the image below**
- **Since this is just for the graph, it's **different** from the final rating (e.g. Overwhelmingly xyz, Mixed, Negative) and changes nothing in that calculation.**

Reference image:
![image](https://github.com/user-attachments/assets/ac1a57aa-ea61-44cf-a1c1-f11a47a19ce4)

**Comment by Klona13** [comment]
@rr- 
it's still showing the graph with less than 5 ratings.
but I think we can lower that to 3 at least to keep it interesting.
It will show this message if there are less than 3:
Not enough ratings to display graph.

**Comment by rr-** [comment]
@Klona13 For older levels with a lot of trle.net reviews but none from TRCustoms, we run into a tricky display issue on the spider graph. Newer levels are going to show a "missing info" message due to insufficient TRCustoms ratings. But for older ones, even if they seem packed with reviews, it might still say "not enough ratings" (or show nothing at all). Users could be confused seeing lots of ratings but getting that message. We should find a neat way to handle this.

One idea is to add a "Legacy" column to the ratings table and show a check mark there, and explain what's it about in the missing info message.

**Comment by Klona13** [comment]
@rr- wdyt of including this in the rating column after the rating text... e.g.
Positive (Legacy)

if 3> ratings:
"Not enough ratings to display graph."
if 3<= ratings, checks if 3<= are TRC ratings, if not...
"Legacy ratings must be updated to display graph."

**Comment by rr-** [comment]
@Klona13 pushed

**Comment by Klona13** [comment]
@rr-  Something doesn't seem right with the graph here... https://staging.trcustoms.org/levels/506/ratings
3 positive ratings and the graph scores extremely low...
![image](https://github.com/user-attachments/assets/e175fae3-7591-42bc-91cb-3f454354e4c7)

**Comment by rr-** [comment]
@Klona13 fixed, and yes, that was a great catch.

**Comment by Klona13** [comment]
@rr-
it doesn't show the message about legacy ratings here:
https://staging.trcustoms.org/levels/3068/ratings
https://staging.trcustoms.org/levels/3070/ratings

but it shows up here:
https://staging.trcustoms.org/levels/2235/ratings
it seems to only show up when there's 1 modern rating.

tested by adding a new rating here, then it appeared:
https://staging.trcustoms.org/levels/2241/ratings

**Comment by rr-** [comment]
Thanks – good catch – it was some leftover code I forgot about that aimed to check for the legacy ratings as well. Fixed
