### ISSUE TITLE
Submission status on lists outside the user profile

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#397]
if a level is yet to be approved, it will show up in the level list similarly to how the user profile list works.

mods and level author(s) can see the status of levels

**Comment by Klona13** [comment]
- [ ] Level author(s) are unable to see their own pending OR rejected level in any list, Currently, only mods can see it and the authors can't check the page without the link.
The approved level message can be seen normally.

**Comment by rr-** [comment]
@Klona13 fixed the second issue, as for the others I can't reproduce locally. Can you show a specific user and level pair? Thanks

**Comment by rr-** [comment]
@Klona13 fixed – the tabs were previously shown or hidden by considering the authored level/walkthrough count, a cached number, for performance reasons. Because this value only tracks approved levels/walkthroughs, a tab wouldn't show if a user had authored only an unapproved level. I changed it to look at all levels and walkthroughs for the logged in user profile, which should be enough to fix the issue.

**Comment by Klona13** [comment]
The level tab seems to be just gone for everyone (including mods+super) except the author.

It seems that only the author can see their own level tab now, other users can't see level tab at all even if it has levels that can already be seen on the level list.

e.g. Let's see Sabatu's profile, he has approved levels that can be seen elsewhere, but not from his profile: https://staging.trcustoms.org/users/876/

**Comment by rr-** [comment]
> The level tab seems to be just gone for everyone (including mods+super) except the author.
> 
> Other users can't see level tab at all even if it has approved levels that can already be seen on the level list.
> 
> e.g. Let's see Sabatu's profile, he has approved levels that can be seen elsewhere, but not from his profile: https://staging.trcustoms.org/users/876/

I forgot to run the script that populates the cached keys – please see now.
