### ISSUE TITLE
Level and review colored text removal

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#399]
Only in the "level form" or "review form". When any markdown coloring is detected in the text box, a warning appears in red underneath:
> Walkthrough color markers will be removed from the text upon submission.

Upon submitting the "level form" or "review form", the following things are stripped from the text:
- [s]
- [/s]
- [p]
- [/p]
- [o]
- [/o]
- [e]
- [/e]
- [t]
- [/t]

Colored text is fine in user profiles; I am anti-fun, but I don't wanna be THAT anti-fun. Some self-expression should be allowed in their own profile.

![image](https://github.com/user-attachments/assets/24b08295-7093-48b8-8b2e-990df66933c5)

**Comment by rr-** [comment]
@Klona13 what if we just remove the buttons to use the colors? Having the warning appear interactively will be kind of difficult.
Also if possible I'd like to keep the tags in the original text, just not color the final text.

**Comment by Klona13** [comment]
Ok. let's proceed with your approach as it's more intuitive that way 👍 

Places where colored text will not render:
- Featured levels in homepage (thank GOD)
- Level description 
- Reviews
- @rr-

**Comment by rr-** [comment]
@Klona13 It's now ready for testing.

**Comment by Klona13** [comment]
@rr- It doesn't seem to work in the 3 places listed, the colored text can still be seen if someone formats it that way.
Also when typing in a textbox with the removed buttons, the preview window increases in size as you type.

**Comment by rr-** [comment]
> @rr- It doesn't seem to work in the 3 places listed, the colored text can still be seen if someone formats it that way (without using buttons). Also when typing in a textbox with the removed coloring buttons, the preview window increases in size as you type.

@Klona13 did you make sure to do a hard refresh with ctrl-f5?

**Comment by Klona13** [comment]
@rr- yes i tried that...
this is also incognito mode
![image](https://github.com/user-attachments/assets/069bd6ca-6db5-4243-8973-dd91462ea389)
