### ISSUE TITLE
Level listing concise dates

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#400]
The updated date should actually refer to a new version of the level, not random updates to the level page. Users who saw the level page aren't interested in checking it again to see what tag changed. This will bring their attention to if the level has a new version instead.

Condition: Date updated should NOT show if it only has a version 1 level file.

This applies on level listings and the level page sidebar.

If it takes the date of the page update, it will show April 1, 2022, 4:05 p.m as the date cause when we went live, that date was placed.

**Comment by Klona13** [comment]
@rr- It's still showing updated date despite all the levels having 1 version. And the updated date should be the date of the latest version of the level instead.
![image](https://github.com/user-attachments/assets/2c6bd898-c4df-42db-993a-7f7ca2463ffb)

**Comment by rr-** [comment]
Gotcha – I'll adjust the migration.

**Comment by rr-** [comment]
@Klona13 fixed

**Comment by Klona13** [comment]
@rr-  same thing here too please! if there's no new version, no point in having the same date
![image](https://github.com/user-attachments/assets/7d80e8bd-79bd-4af8-950e-171bb000b0ac)

**Comment by rr-** [comment]
Done – it's now deploying.
