### ISSUE TITLE
Action buttons for reviews and ratings tabs

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#401]
1. This is the button position. If there's a review by you already, it will no longer show up as the edit button will be next to the review itself anyway as it is in prod.
![image](https://github.com/user-attachments/assets/1ea8dc3d-8b6c-43a2-b910-6ca81209832f)

2. Form shows on the same page, but reviews hide. The Submit / Update review button changes depending on if there's already a review or not.
![image](https://github.com/user-attachments/assets/62e2adfc-cbfc-492f-9d3c-a46b3a37c76b)

3. For ratings page, it would be the same. The button on the upper left corner "Add rating" / "Update rating"
4. The questionnaire shows up, replacing the spidergraph and the user rating list.
5. Note to direct to their respective tabs when submitting the forms or updating them.

**Comment by Klona13** [comment]
As discussed, the questionnaire page will be like a wizard. Split into 5 sections with "Previous" and "Next" buttons.

**Engagement**

> 1- Do you plan on revisiting this game?
> 2- What did you think of the length of the game? 
> 7- The level lived up to the expectations set by the information on the level page. 
> 9- Ingame actions were random and lacked real sense; they felt unrelated to the story/context.

**Uniqueness**

> 4- The level featured enjoyable unique things I have never seen before.


**Quality**

> 3- The visual quality was consistently good throughout the game. 
> 5- The sound design enhanced the game's environment and set pieces. 
> 6- The builder was able to set an atmospheric tone and immerse the player. 

**Enjoyment**

> 8- How often did you get bored due to unintuitive, messy, or repetitive game design?  
> 10- What did you think of the game's difficulty? 
> 11- The level was overall fun and fulfilling in the end. 

**Stability**

> 12- There were visual glitches. 
> 13- There were audio issues. 
> 14- There were gameplay bugs.
> 15- There were bugs/problems that seriously ruined my experience.

**Comment by Klona13** [comment]
the review form doesn't match the style of other text boxes in preview tab mode
![image](https://github.com/user-attachments/assets/75db0072-4bb9-4458-8edc-cef8c339a48c)
![image](https://github.com/user-attachments/assets/22114ef7-7efe-40f8-890c-71e920dc4b53)

**Comment by rr-** [comment]
It's on purpose as taking away this space from the user squeezes the textarea even more. Use case that highlights this issue: side by side markdown preview + mobile. LMK if I should change it nonetheless or maybe do some conditional tweaks.

**Comment by Klona13** [comment]
@rr- it still wont let me submit the rating questionnaire
