### ISSUE TITLE
User registration action required but no actions

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#403]
1. A user registered and tried to claim a TRLE.net user.
2. They didn't pass the check so it was rejected.
3. A few minutes later they register again I think... but there's no mod actions available on the profile.
4. In AD it says email confirmed, but there's no email address.

![image](https://github.com/user-attachments/assets/3957fc1f-ce3a-4bb0-845d-6ebe35b0f8af)
![image](https://github.com/user-attachments/assets/6daa1d7e-4ab5-4e9a-a1f2-d671b55cab2f)
![image](https://github.com/user-attachments/assets/53657791-48ca-40d8-865e-9c56ba932e38)

**Comment by rr-** [comment]
@Klona13 I don't know how to reproduce this outcome, at least without manually fiddling with the account's properties in the admin.

**Comment by Klona13** [comment]
Token related.
Affects email confirmation links and password reset, allowing infinite uses within time allowed
fix pushed by dash, testing
