### ISSUE TITLE
Review/Ratings rewording

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#405]
Since the data is based on ratings now, some places where the word "review" was used should now be "rating"

- [x] Homepage

![image](https://github.com/user-attachments/assets/8915db3e-3889-4527-a954-b3c5b42d0c8e)

- [ ] Level list (also the number here should be based on the amount of ratings now, not reviews)

![image](https://github.com/user-attachments/assets/3eae19d3-954e-4b3f-8f52-26cc1a039fe1)

**Comment by Klona13** [comment]
@rr- this number is staying at 0 and not changing
![image](https://github.com/user-attachments/assets/8e9c7102-bafd-47b9-908b-4586926c8212)

**Comment by rr-** [comment]
@Klona13 fixed
