### ISSUE TITLE
Make the rating questionnaire a wizard

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#407]
As discussed, the questionnaire page will be like a wizard. Split into 5 sections with "Previous" and "Next" buttons.

**Engagement**

> 1- Do you plan on revisiting this game?
> 2- What did you think of the length of the game? 
> 7- The level lived up to the expectations set by the information on the level page. 
> 9- Ingame actions were random and lacked real sense; they felt unrelated to the story/context.

**Uniqueness**

> 4- The level featured enjoyable unique things I have never seen before.

**Quality**

> 3- The visual quality was consistently good throughout the game. 
> 5- The sound design enhanced the game's environment and set pieces. 
> 6- The builder was able to set an atmospheric tone and immerse the player. 

**Enjoyment**

> 8- How often did you get bored due to unintuitive, messy, or repetitive game design?  
> 10- What did you think of the game's difficulty? 
> 11- The level was overall fun and fulfilling in the end. 

**Stability**

> 12- There were visual glitches. 
> 13- There were audio issues. 
> 14- There were gameplay bugs.
> 15- There were bugs/problems that seriously ruined my experience.

**Comment by rr-** [comment]
@Klona13 this is ready for testing.

**Comment by Klona13** [comment]
@rr-  

### Updating
When UPDATING an old rating, the selections are empty:
![image](https://github.com/user-attachments/assets/afd53927-b758-456f-b099-a408b62eea0f)

This issue does not happen again after updating the rating through the wizard one time.

### Back button
It should let the user go back without filling anything
![image](https://github.com/user-attachments/assets/bee7287d-a21c-4b28-b933-14b086de82fb)

**Comment by rr-** [comment]
@Klona13 
re: 1 I think you're editing a legacy TRLE review.
re: 2 Fixed.
