### ISSUE TITLE
Selectable stuff always lit up

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#408]
I noticed this affects text boxes and dropdown lists.

## Staging
Always lit up even if not selected
![image](https://github.com/user-attachments/assets/5bef75d7-a6fe-4e23-8330-fe1713d8ddc6)

# Prod
Unlit when not selected, and lights up when selected correctly
![image](https://github.com/user-attachments/assets/8a7d45ff-765a-4443-b49f-38aaa7391706)
![image](https://github.com/user-attachments/assets/eec40566-0cf9-4d1f-9020-116bfb4a3ace)

**Comment by rr-** [comment]
@Klona13 this is ready for testing.
