### ISSUE TITLE
Automatically add and mark rated/reviewed levels in Playlist as "Finished"

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#410]
A one time message for people who rate or review, replacing the one that pops up every time.

>Would you like to automatically add rated/reviewed levels to your playlist and mark them as "Finished" from now on?
>This setting can be changed any time from the Settings tab.

>Yes / No

Yes will check the setting, no will uncheck.

Maybe this specific setting is saved in the user record so it's the same across all devices?

![image](https://github.com/user-attachments/assets/f6e6548a-8e00-4310-b959-69e10aa81a4f)

**Comment by rr-** [comment]
@Klona13 took a bit different approach, let me know if you like it

![Image](https://github.com/user-attachments/assets/333fae18-771c-4463-8c23-435c393d39e0)
![Image](https://github.com/user-attachments/assets/ee398ac6-67a3-42b8-93c5-c3e4aae799fd)
