### ISSUE TITLE
Level updated date - Deleting a version

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#424]
Usually some times authors may upload several versions after rejection and I delete them from AD some times after switching the uploaded file to version 1.

The problem is when a new version is uploaded, it seems that the updated date will not go away even after removing all except version 1.

Can there be a check for **NOT** displaying the updated date? If there's only 1 version, don't show.

**Comment by Klona13** [comment]
No.
1. copy the "uploaded file ID" of V2 level file
2. paste the it in V1 level file and save
3. Delete V2

**Comment by rr-** [comment]
@Klona13 fixed in staging and on prod. Didn't run the script to sync the dates, LMK if I should.

**Comment by Klona13** [comment]
sync dates? you mean of the version 1 to the release date for TRLE.net imports? no need for that as there is no guarantee that it's a version from that date.

TRLE.net versions used to get updates too and they're mentioned in its description, and some times they didn't mention it at all.

So for all levels, the V1 date should stay the same date as when it was actually uploaded. Even if the level page was made 1 Dec and the version 1 was uploaded 2 Dec.

**Comment by rr-** [comment]
@Klona13 when I say `sync`, I mean to force sync the cached properties. The updated date of a level is one such property. NB I just did and it fixed the issue for existing levels.
