### ISSUE TITLE
Donation - User Profiles

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#60]
Users can add their Ko-Fi.

**Comment by rr-** [comment]
@Klona13 does it have to be ko-fi? Why impose this, can't it be an additional link like the website?

**Comment by Klona13** [comment]
I want to limit this to Paypal and Ko-Fi cause it cause they are common I think. Ko-fi seems like a nice place to support builders steadily if it ever takes off.

**Comment by rr-** [comment]
Let me reword.
Do I HAVE to validate that it's Paypal or Ko-Fi or is it OK if I just accept any link here? (Time cost)

**Comment by Klona13** [comment]
Yes, it needs to be validated.

**Comment by rr-** [comment]
Added some stupid validation. It's possible to trick it with links such as this
https://example.com/?paypal.com
but I don't think this matters as people can put whatever they want in their bio anyway.
