### ISSUE TITLE
Reviews Tab

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#77]
Add a new tab called Reviews.

# Sidebar
Inside the sidebar, there are TWO boxes like the homepage's featured levels area.
1. Reviewer Catalogue
Link text: Find more reviewers
Description: "Search our database for custom level reviewers."
Function: Takes you to a new page where you can search for reviewers just like searching for levels.
On that page, there's a sidebar where you can search for user profiles here using:
- Username
- Number of reviews (Slider)

Users who haven't posted a review do not show up at all. This currently happens in the Levels tab for users who only have reviews, which is totally fine.

2. Least reviewed levels
Link text: Review less known levels
Description: "A list of levels with less than 5 reviews, ordered by oldest release date."
Function: It takes you to a page with just a list of levels that fit the criteria, which is levels with less than 5 reviews ordered by oldest release date.

# Latest Reviews
It shows a list of the latest reviews, up to 25.
If the review is longer than 1200 characters, there will be a "... (read more)" at the start of the next line.
Clicking on it expands the text, showing "(read less)" at the end, which will minimize the text again.
When a new one is posted, the oldest one at the bottom goes away.

**Comment by rr-** [comment]
Mockups needed.
What is a "summary of a review"?

**Comment by Klona13** [comment]
@rr- New mockup. THOUGHTS?
![image](https://user-images.githubusercontent.com/93257509/177051124-f4e8606f-7ad7-4d25-a701-14ff96065321.png)

**Comment by rr-** [comment]
@Klona13 I added what you asked but took shortcuts.

I didn't add the small expandable box with the level info because it causes the layout to jerk and that's a bad thing. Next, it requires adding a separate endpoint to retrieve a level for this information box.

Second, I didn't add slider to the number of reviews. LMK if it's needed and if so in what form. Sliders are hard to code.

Third, I don't have the reviewer catalogue GFX so no image.

**Comment by Klona13** [comment]
Reviewer's Catalogue
![RevCat](https://user-images.githubusercontent.com/93257509/177241510-aa827388-ea85-461a-8f04-612289127eee.jpg)



Less Known Levels
![LesKnoLev](https://user-images.githubusercontent.com/93257509/177241518-04238faa-0384-41b5-8120-b5993e0f344d.jpg)

**Comment by Klona13** [comment]
> I didn't add the small expandable box with the level info because it causes the layout to jerk and that's a bad thing. Next, it requires adding a separate endpoint to retrieve a level for this information box.
Oh yeah, I thought it looked weird also. This is good now.

> Second, I didn't add slider to the number of reviews. LMK if it's needed and if so in what form. Sliders are hard to code.
It's fine then, we can drop that. But I thought of something better and simpler.
A checkbox to hide inactive reviewers. It hides reviewers who haven't reviewed anything for more than 6 months.
It would be placed between the search box and the reset button.

> Third, I don't have the reviewer catalogue GFX so no image.
See last comment.

**Comment by Klona13** [comment]
@rr- 
This would look nicer for the search page. It shows each user's image also. In the future, the list that would show builders in the extras tab author's map would have the same look.
![image](https://user-images.githubusercontent.com/93257509/177317494-fad7dca2-140d-467d-bdc7-04dc3269f4f5.png)

**Comment by Klona13** [comment]
Cannot search here if signed out.
![image](https://user-images.githubusercontent.com/93257509/177351103-87e98072-ff5b-4efd-bff1-d6600043da4b.png)

Images don't resize properly to fit the 1:1 frame.
![image](https://user-images.githubusercontent.com/93257509/177351282-960f6ab6-f020-4e57-8097-24ad0b080d32.png)
