### ISSUE TITLE
Make modals fancier

### ISSUE THREAD

**Issue by rr-** [rr-/TRCustoms#81]
Currently there are a few places where we do plain `prompt()`, `confirm()` and `alert()`. I should create beautiful widgets for these that match the website style.

**Comment by Klona13** [comment]
Note: the custom modals should have X button on top right corner. (Gonna be needed for the walkthrough modals).

**Comment by rr-** [comment]
Testing scenarios:

| Model  | Action       | Modal
| ---    | ---          | ---
| Level  | Approval     | confirmation
| Level  | Deletion     | confirmation
| Level  | Rejection    | prompt for reason
| Review | Deletion     | confirmation
| Tag    | Deletion     | confirmation
| Tag    | Merge        | prompt for target tag name
| Tag    | Rename       | prompt for new tag name
| User   | Activation   | confirmation
| User   | Deactivation | prompt for reason
| User   | Ban          | prompt for reason
| User   | Unban        | confirmation

**Comment by Klona13** [comment]
Gonna edit this post while testing:

| Model  | Action       | Modal
| ---    | ---          | ---
| Level  | Approval     | confirmation 
| Level  | Deletion     | confirmation
| Level  | Rejection    | prompt for reason
| Review | Deletion     | confirmation
| Tag    | Deletion     | confirmation
| Tag    | Merge        | prompt for target tag name
| Tag    | Rename       | prompt for new tag name
| User   | Activation   | confirmation
| User   | Deactivation | prompt for reason
| User   | Ban          | prompt for reason
| User   | Unban        | confirmation
