### ISSUE TITLE
Home Page - Skeleton

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#86]
HOME PAGE (Design Reference)

```
Side Bar
"Statistics"
Total number of levels, broken down to engine types (TR12345 like TRLE.net) Don't show TEN yet.
Number of Reviews
Number of Walkthroughs (% of levels that have at least one submitted)

"Extras"
- Event Catalogue
- Builder Interviews
- Map of Authors
```
```
Body:
- News/Annoucements (Can see up to the last 10 annoucements)
- Featured Levels
```
Note: For now, add extras section in sidebar, but under it say "Coming Soon!" instead of the 3 links cause those features will be post-launch.
![image](https://user-images.githubusercontent.com/93257509/156451981-ec2223a5-3d37-479d-8946-4267f7ced175.png)

**Comment by rr-** [comment]
I made it possible to specify multiple authors because it was easier.
Instead of embedding a form I created a button in the sidebar as in other pages.

**Comment by Klona13** [comment]
Can you write "More features coming soon...!" under **Extras**? :)
![image](https://user-images.githubusercontent.com/93257509/157351703-6a1974ff-2ec7-467e-8918-595e1c18d152.png)
