### ISSUE TITLE
Extra Tab Page - Interviews

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#87]
Uses walkthrough list style.
![image](https://user-images.githubusercontent.com/93257509/230067184-5a5c46b1-dd7c-4f97-9d57-110251e781f6.png)

Columns:
- "Go to interview" (the clickable link)^
- Interviewee
- Interviewer
- Date interviewed (filled manually, and also this will be the default order)
- Date submitted

At the top of the page, there's a button that says "Submit an interview", the user must fill the following:
- Interviewee user
- Date interviewed
- Interview text
- [Submit] button

Once submitted, it appears in the audit log and must be approved before it appears on the list. If rejected, a notification appears at the top of the interview page. No emailing involved.

When you click to read interview, you are taken to a page that contains info like this:
![image](https://user-images.githubusercontent.com/93257509/230066445-f3a7828e-7007-455a-8f7f-d33cc01028c5.png)

There is another button that only the superuser can see: "Edit page"

**Comment by Kubsy** [comment]
I have a question about this function but will anyone be able to interview someone? Or will we have to get Mod's approval and etc?

**Comment by Klona13** [comment]
It needs to be submitted via email.

**Comment by rr-** [comment]
@Klona13 is it OK if we make it possible to edit this from Django Admin only? (pros: easy to implement) Or do we want to make it editable via the website (pros: we get the Markdown editor this way)
