### ISSUE TITLE
Emails - No Reply Notifications

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#95]
A no reply email address for sending automatic emails for:

- [x] Email verification
- [x] Password reset
- [x] Notifications:
    - [x] User welcome
    - [x] User rejected
    - [x] User banned
    - [x] User ban lifted
    - [x] Level submitted
    - [x] Level approved
    - [x] Level rejected
    - [x] Review posted
    - [x] Review edited
    - [x] ~~Walkthrough posted~~
    - [x] ~~Walkthrough edited~~

**Comment by rr-** [comment]
Needs more details and template for each message as well as information whom to notify.

**Comment by Klona13** [comment]
Subject:
```Password Reset```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

We have received a request to reset the password for your account at TRCustoms.org.

To reset your password, click on the button below:
<button>

If you cannot click on the button, please use this link:
<link>

In case you received this email without requesting for a password reset, please contact admin@trcustoms.org about this incident.

Regards,
TRCustoms.org```

**Comment by Klona13** [comment]
Subject:
```Welcome to TRCustoms.org```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

Welcome to TRCustoms.org! Thank you for your patience during the activation process.

Now that your account is fully functional, you will be able to upload levels, write reviews, and much more. If you previously had a profile on trle.net, you will have access to that profile's content.

We will be looking forward to your submissions!

Regards,
TRCustoms.org
```

**Comment by rr-** [comment]
@Klona13 can you edit the ticket and for each email template, put a subject and the intended body underneath?

**Comment by Klona13** [comment]
Subject:
```Registration Rejected```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

Apologies, but your registration at TRCustoms.org has been rejected.

Reason:
<reason>

Regards,
TRCustoms.org
```

**Comment by Klona13** [comment]
Subject:
```Account Banned```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

Your account at TRCustoms.org has been banned.

Reason:
<reason>

Regards,
TRCustoms.org
```

**Comment by Klona13** [comment]
Subject:
```Level Submitted```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

You have successfully submitted a level at TRCustoms.org! Click here (<-link) to go to the level page.

Kindly wait until your level is approved by the Mod Team.

You can view the status of your level by clicking the "My Levels" button on your profile to see a list of your submitted level(s).

Regards,
TRCustoms.org
```

**Comment by Klona13** [comment]
Subject:
```Level Approved```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

<level name> has been approved and is now available for public download on TRCustoms.org.

Regards,
TRCustoms.org
```

**Comment by Klona13** [comment]
Subject:
```Level Rejected```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

<level name> has been rejected.

Kindly review your level submission based on the reason provided by the Mod Team:
<reason>

Regards,
TRCustoms.org
```

**Comment by Klona13** [comment]
Subject:
```Review posted```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

You have submitted a review for <level name>.

Based on the questionnaire you answere, your review will be labelled as <positive/mixed/negative>.

Regards,
TRCustoms.org
```

**Comment by Klona13** [comment]
Subject:
```Review edited```

Body:
```
<LOGO> TRCustoms.org 
(Boxed in the middle)
Hi <user>,

The review submitted for <level name> has been edited.

Regards,
TRCustoms.org
```

**Comment by rr-** [comment]
@Klona13 shouldn't the review alert go to the level author rather than the reviewer? If I reviewed a level, I know what I just did, no need to spam my mailbox about that. On the other hand, if I authored a level, I'd prefer to get notified about new reviews.

**Comment by Klona13** [comment]
Right! Let me edit that.

**Comment by Klona13** [comment]
Testing
- [ ] Email verification
- [ ] Password reset
- [ ] Notifications:
    - [ ] User welcome
    - [ ] User rejected
    - [ ] User banned
    - [ ] User ban lifted
    - [ ] Level submitted
    - [ ] Level approved
    - [ ] Level rejected
    - [ ] Review posted
    - [ ] Review edited

**Comment by Klona13** [comment]
I don't receive a "level rejected" email.

**Comment by rr-** [comment]
@Klona13 Are you the uploader? Authors do not receive this email to prevent abuse:

1. Troll sets DJ Full as the author
2. Mod reject this level
3. The mail goes to Troll, not DJ Full

**Comment by Klona13** [comment]
@rr- 
Yes.
For the same level I received Level submitted and Level approved, but not the rejection email.

**Comment by rr-** [comment]
I tested it and it works for me. Which level?

**Comment by Klona13** [comment]
https://trcustoms.org/levels/3372
Must have happened when I uploaded from the other account.

I uploaded the new version from the other account and it worked.
